### ISSUE TITLE
xquery-helper goToFunction not working

### ISSUE THREAD

**Issue by christophe-g** [eXist-db/eXide#10]
Navigate > go to Definition and outline were not working with the distribution I am using. 

A few patches here https://github.com/krikrou/eXide/tree/patches.
(or, better: https://github.com/krikrou/eXide/commit/90198649d23d479ab8ea839eb14df9375a0f7889#L2L352)

Sorry, cloned your repository locally and pushed it back to gitHub, thinking that I could also pass pull request this way, but does not seem to work...

Cheers,
C.

**Comment by wolfgangmm** [comment]
Thanks. I applied this patch.
