### ISSUE TITLE
Glitches in final character of XQuery snippets

### ISSUE THREAD

**Issue by joewiz** [eXist-db/eXide#105]
I've noticed some glitches affecting the final characters of snippets in certain circumstances.  For example, when I use the snippet `fun` in a library module, I get this:

``` xquery
declare function name($param) 
    ()
};{
```

Notice that the final character of line 3, a `{`, should be the final character of line 1.  

I don't see this glitch when editing a main module. But I **can** reproduce the problem if I am in a library module. For example, paste this query in, and then trigger the `fun` snippet:

``` xquery
xquery version "3.0";

module namespace blah="blah";
```

Similarly, in the same scenario, if I use the snippet `tei`, the final semi-colon is pasted onto the 2nd line:

``` xquery
declare namespace tei="http://www.tei-c.org/ns/1.0"
;
```

Similarly, if I use the snippet `html5`, the semi-colon from the 1st line is moved to the final character of the 2nd line:

``` xquery
declare option output:method "html5"
declare option output:media-type "text/html";;
```

In sum, the problem appears to be that the final character from the first line of the snippet is moved to the final character of the final line.

**Comment by marmoure** [comment]
@joewiz can you please confirm if this issue still exists as i tested the different scenarios and it's seems to be working as expected

**Comment by joewiz** [comment]
@marmoure You're quite right! I am no longer able to reproduce the bug with the above steps or by activating any of the snippets in https://github.com/eXist-db/eXide/blob/develop/templates/xquery.snippets. 

Thus, I'll close this issue.
