### ISSUE TITLE
Can't open xqm files

### ISSUE THREAD

**Issue by Flamenco** [eXist-db/eXide#11]
Files with extension .xqm extensions are filtered, and do not show up in the open dialog.

**Comment by wolfgangmm** [comment]
I could not reproduce this, sorry. As far as I can see, there's no filtering applied. If you are still having the issue, could you describe it in more detail?

**Comment by shabanovd** [comment]
Permissions?

**Comment by Flamenco** [comment]
It turns I had several very long filenames and they were pushing the extensions out of view.  Closing, and thank you for confirming a Works-For-Me.
