### ISSUE TITLE
Add download button to DB Manager view

### ISSUE THREAD

**Issue by joewiz** [eXist-db/eXide#111]
Currently in eXide, to download a file, you must first open the file and then select File > Download. Some files are so large that opening them is slow - inefficient just to download a file. It would be very convenient if the DB Manager view (File > Manage) could add a Download button to download a selected resource. 

The ability to download collections is less important, but perhaps if a download feature were to be extended to collections (or multiple selected resources), the selected collections/resources could be downloaded as a zip file - much as the Application > Download App button does.

**Comment by marmoure** [comment]
Hi @joewiz seems like getting selected resources in eXide in the current state doesn't support selecting collections or multiple resources, you can only select one resource
