### ISSUE TITLE
Logged-in status is suddenly lost, must re-authenticate with each save

### ISSUE THREAD

**Issue by joewiz** [eXist-db/eXide#115]
After some period of using eXide to develop apps, while logged in as admin (without checking "remember me), eXide appears to forget my logged-in status. The symptom is that saving a file in XQuery brings up the login dialog. It prompts me to reauthenticate upon each save. The only sure fire fix is closing all eXist browser windows and deleting localhost app data. Shift-click on the reload button does not fix the issue.

This is using the latest Chrome on the latest Mac OS X. Not to say this is recent - this has affected me for some time. But the issue is intermittent, so I don't have easy steps to reproduce. I would be happy to supply more information if you can suggest a method of probing the session.

**Comment by joewiz** [comment]
While I still experience random logouts in eXide (even today), I am still unable to find reproducible steps. This happened to me today while using eXide. I was logged in, saving documents, running tests, and suddenly got prompted to log in again. Monitoring requests via Chrome's developer tools, I noticed that monex's login has no "remember me" option, but it uses the persistent login module and sets the duration to 7 days. Perhaps some combination of having monex logged in with its defaults, and then choosing a different login method (i.e., without "remember me") in an app like eXide results in some confusion? 

Has anyone else been able to reproduce this?

**Comment by shabanovd** [comment]
@joewiz next time try to delete cookies (report what cookies was set, one or two and what `path` it have) and reload page (only that 2 steps)

**Comment by joewiz** [comment]
Thankfully, I have not seen this happen in ages.
