### ISSUE TITLE
QOL improvement for resetting UI

### ISSUE THREAD

**Issue by duncdrum** [eXist-db/eXide#116]
Most users probably have a set of preferences for how the eXide UI looks, for local machines, test, and live servers. Yet, I have to reset those preferences on my systems on a daily basis. Since eXide looses them when  different systems are called from within the same browser.  It would be nice if admins could set the UI preferences to their liking and permanently change the default values. 
![screenshot 2015-10-26 12 03 55](https://cloud.githubusercontent.com/assets/6205362/10727531/e42851fa-7bda-11e5-883f-29027bd07958.png)

**Comment by dizzzz** [comment]
what browser do you use? revision?

you actually define a solution, better to describe the issue more isolated? I find it difficult to understand your problem description....

**Comment by duncdrum** [comment]
this has been happening with Safari, Chrome and Firefox on OS X since before eXist v.2. I've tried to only open eXide in one type of browser but within two or three uses the UI preferences reset to default.
