### ISSUE TITLE
Add option to disable auto-pair of quotes, parens, etc.

### ISSUE THREAD

**Issue by joewiz** [eXist-db/eXide#117]
I've never gotten used to eXide's auto-pair function.  This is where you type a single `"` and get two - `""` - with your cursor placed between them.  The same behavior affects `'`, `(`, and `{`.  Often, when I am trying to insert a single instance of these characters, the editor inserts two.  Then I delete one, but the editor deletes both.  This can be maddening and leads to many extraneous key presses.  I imagine some developers are used to this behavior from other code editors, but for me - and I'd bet - many new users, typing one thing and having something else happen is disconcerting and leads to wasted keypresses. 

Would it be possible to add a preference disabling this?

Caveat: I would hope that this preference wouldn't disable the autocompletion of elements, e.g., `<x>as soon as I type </`immediately becomes `<x>as soon as I type </x>`.  This generally works well - not perfect, but on balance is a time saver.  Also valuable is the snippet behavior, where I can type a code like `html`, tap control-space, and `html` is replaced by some XQuery code.

**Comment by marmoure** [comment]
@joewiz This is pretty much the standard behaviour in every IDE at this point  trying to do a double quote will always produce `""` with the cursor in between ,to minimize clicks you can click on `Del` which should delete the back pair.
If you still think this is a problem we can try to take out keyboard control from [ACE](https://github.com/ajaxorg/ace) and try to manipulate it before passing it to the editor again.
