### ISSUE TITLE
Resource names are double-encoded on store

### ISSUE THREAD

**Issue by joewiz** [eXist-db/eXide#119]
Steps to reproduce (using eXist RC1 with eXide 2.1.3):
- create new XML file in eXide
- save as `/db/téste.xml`
- note that the directory pane and file > open/manage panes show encoded name:

> <img width="308" alt="screen shot 2015-11-26 at 1 37 33 pm" src="https://cloud.githubusercontent.com/assets/59118/11429225/f7ff14b8-9442-11e5-9a14-971bb7a8c24b.png">
- note that attempting to open this file via directory or open/manage fails with:

> Request URL:http://localhost:8080/exist/apps/eXide/modules/load.xql?path=/db/t%C3%A9ste.xml
> Request Method:GET
> Status Code:404 Not Found
- however deleting the file via file > manage succeeds:

> Request URL:http://localhost:8080/exist/apps/eXide/modules/collections.xql?remove%5B%5D=t%25C3%25A9ste.xml&root=%2Fdb
> Request Method:GET
> Status Code:200 OK

I think the solution involves applying `xmldb:decode()` to the `$resource` variable (at https://github.com/wolfgangmm/eXide/blob/develop/controller.xql#L117), so that this path is in its decoded state before being passed to `store.xql`. But I wasn't able to complete testing on this.

**Comment by hungerburg** [comment]
The value of $request in controller.xql **is already encoded**; console:log() it and see monex print "t%C3%A9ste". It is then forwarded to store.xql where it gets **encoded once more** and turned into "t%25C3%25A9ste", see https://github.com/wolfgangmm/eXide/blob/develop/modules/store.xql#L58 - Rather leave as is, than decode/recode, not?

**Comment by ambs** [comment]
Note that if the string is "(foo)" it gets correctly encoded, and not double encoded. So, there is some inconsistency. I do not think leaving things as they are to be good (neither professional). If it is a bug we should fix it (My humble opinion).

**Comment by hungerburg** [comment]
Depends on what you think needs encoding at all; RFC 3986 governs URIs, and there "A-Z a-z 0-9 - . _ ~ ! $ & ' ( ) \* + , ; = : @" are all allowed to appear literally in a PATH; eXist-db REST interface mirrors that (current trunk build)' and DAV interface did so since its beginning IIRC:
`curl -u admin: -T '/tmp/(foo)' http://localhost:8080/exist/rest/db/test/`
In the host filesystem you will get file '(foo)'; Yet, eXide now will not find it! So: it is not only about storing but about fetching too…

**Comment by ambs** [comment]
Exactly. Saving through eXide will encode ( and ).

**Comment by joewiz** [comment]
@hungerburg I recall you doing some extensive research into this. Do you by chance have (or if not, could you come up with) a list of resource and collection names that eXist needs to be able to store correctly, and the correct encoding for these (i.e., expected results)? Then we can test eXide's behavior against these?

**Comment by hungerburg** [comment]
@joewiz Basically, IMHO eXist needs to be able to store anything a monkey behind a typewriter can come up with. Encoding is more tricky: See https://github.com/eXist-db/exist/commit/8e4cea6104702af4fc51b5d2cdedf9c36acacdb5

**Comment by joewiz** [comment]
superseded by #151.
