### ISSUE TITLE
New branch needed for eXist versions supporting xmldb:store-as-binary (and not)

### ISSUE THREAD

**Issue by joewiz** [eXist-db/eXide#120]
@wolfgangmm You probably realized this (sorry I didn't until now), but the current `store.xql` depends on the 3.0 develop branch's support for `xmldb:store-as-binary()`. See:
- https://github.com/eXist-db/exist/commit/9c6bfd099a806328c352217100bc19189e9c5372
- https://github.com/wolfgangmm/eXide/commit/1d46357d7c5659d9459bcd2733aa5627f3af087a

Do we need two branches of eXide?  One for 3.0RC1 and earlier, and one for the recent develop branch and sooner?  I know the public repo supports this kind of versioning, but I'm not sure how to approach this with git.  

Or do you plan to back-port this function to 2.2?

**Comment by wolfgangmm** [comment]
This is still a problem with the versioning scheme in eXist: the repo cannot distinguish between RC1 and RC2 or 3.0 final. We thus cannot upload eXide with this function being used.

However, we could change the code to use a dynamic function lookup and fallback if it is not present.

**Comment by joewiz** [comment]
That sounds like a good approach. I recall seeing that technique before but forget where. Can you point me to an example of where you've done that? If so, I can give it a try.

**Comment by joewiz** [comment]
@wolfgangmm I searched a number of repos and couldn't find the example I remember once seeing, so I thought I'd take a stab.  Is this the basic idea?  This would take the place of https://github.com/wolfgangmm/eXide/blob/develop/modules/store.xql#L70-L83.

``` xquery
let $store-as-binary-available := exists(util:registered-functions('http://exist-db.org/xquery/xmldb')[. eq xs:QName('xmldb:store-as-binary')])
let $store-as-binary-function :=
    if ($store-as-binary-available) then
        xmldb:store-as-binary#3
    else
        xmldb:store#3
let $isNew := not(util:binary-doc-available($path)) and not(doc-available($path))
let $path :=
    if (util:binary-doc-available($path) and $store-as-binary-available) then
        $store-function($collection, $resource, $data)
    else
        if ($mime) then
            xmldb:store($collection, $resource, $data, $mime)
        else
            xmldb:store($collection, $resource, $data)
return (
    if ($isNew) then
        local:fix-permissions($collection, $resource)
    else
        ()
```

**Comment by joewiz** [comment]
Hmm, apparently not. I just tested this on 3.0RC1 and got this error:

```
Cannot compile xquery: err:XPST0017 Function xmldb:store-as-binary() is not defined in module namespace: http://exist-db.org/xquery/xmldb
```

**Comment by wolfgangmm** [comment]
xmldb:store-as-binary#3 will still resolve the function at compile time and thus result in an error. I would use a dynamic lookup as follows:

``` xquery
declare variable $local:store-as-binary := function-lookup(xs:QName("xmldb:store-as-binary"), 3);
```

**Comment by joewiz** [comment]
Thanks for the tutorial in this technique!
