### ISSUE TITLE
range index not working as expected

### ISSUE THREAD

**Issue by sonymoparthi** [eXist-db/eXide#124]
My xml file is with the structure:

```
<compound>హరి ర్హరతి<parts>హరిః హరతి</parts></compound>
<compound>తద్విష్ణోః<parts>తత్ విష్ణోః</parts></compound>
```

I have created a range index:

```
<range>
    <create qname="compound" type="xs:string"/>
</range>
```

I expected the index terms are `హరి ర్హరతిహరిః హరతి` and `తద్విష్ణోఃతత్ విష్ణోః` but I found `హరి ర్హరతి` and `తద్విష్ణోః` under index link in monitoring and profiling window. And also the search string:

```
//compound[.="హరి ర్హరతిహరిః హరతి"] 
```

giving 0 results.

Can any one help in creating index on the whole contents of compound like `హరి ర్హరతిహరిః హరతి`, `తద్విష్ణోఃతత్ విష్ణోః` so on?

**Comment by joewiz** [comment]
@sonymoparthi This is a general eXist question, not an eXide question. Please move this issue to https://github.com/eXist-db/exist/issues.

**Comment by joewiz** [comment]
Moved to https://github.com/eXist-db/exist/issues/974.
