### ISSUE TITLE
File Manager does not copy, only cuts

### ISSUE THREAD

**Issue by janhejzl** [eXist-db/eXide#125]
I work with eXide packed with eXist-db 3.0.RC1 and it really seems eXide’s file manager does not support copying of files, it always cuts them. It is not apparent, the button Copy works but when I paste files somewhere, they disappear from the original location.

**Comment by joewiz** [comment]
I'm unable to reproduce this with the current develop branch of eXist and eXide.  Copy works as expected.

**Comment by janhejzl** [comment]
Me neither. I was restructuring many things in one moment and the problem was probably associated with some conditions I can’t reproduce again. Closing.

**Comment by joewiz** [comment]
Good to hear!
