### ISSUE TITLE
Function lookup/validation failures with math functions

### ISSUE THREAD

**Issue by joewiz** [eXist-db/eXide#128]
Looking up `math:pow` (via Navigate > Function doc or F1) returns 0 results, but looking it up as `pow` yields the documentation for the function, but without its `math` namespace prefix. When selecting this function to autocomplete the function signature, eXide says (correctly) that there is no `pow` function in the default function namespace.

**Comment by dizzzz** [comment]
hmmmm Interesting..... I have no idea :-)

**Comment by joewiz** [comment]
The autocomplete request goes to <http://localhost:8080/exist/apps/eXide/modules/docs.xql>, with the POST parameter `prefix=math:pow`. The call to docs.xql returns `null`. The docs.xql module's handling of this parameter begins at https://github.com/wolfgangmm/eXide/blob/develop/modules/docs.xql#L120-L127. 

I've got a PR to fix this, coming shortly.

**Comment by joewiz** [comment]
Function doc on `math:pow`:

> <img width="436" alt="screen shot 2016-12-05 at 4 55 30 pm" src="https://cloud.githubusercontent.com/assets/59118/20904045/d688065a-bb0b-11e6-8301-bc1340e74ef3.png">

Autocomplete on `pow`:

> <img width="365" alt="screen shot 2016-12-05 at 4 53 55 pm" src="https://cloud.githubusercontent.com/assets/59118/20904081/03f6d404-bb0c-11e6-8bf8-6eaffec984fc.png">

One source of the problem is that the functions in `map` and `array` modules contain the module namespace prefix in the function names, e.g., `@name="map:contains"`, whereas in the `math` module, the same attribute lacks the prefix, e.g., `@name="pow"`. Perhaps this math module oddity has to do with the namespace "collision" between the native eXist math module and the math namespace functions added in XQuery 3+.

My PR accounts for **searches** with and without namespace prefixes, and for **function documentation** with and without namespace prefixes.

**Comment by joewiz** [comment]
For comparison, here is the "before" when doing function completion on `pow`:

> <img width="380" alt="screen shot 2016-12-06 at 8 04 40 pm" src="https://cloud.githubusercontent.com/assets/59118/20950759/97638230-bbef-11e6-8178-7bd052389689.png">

Selecting either of these would immediately yield an error that there is no `pow()` or `power()` function in the default function namespace.

Also, trying completion on `math:` or `math:pow` returned 0 results.

**Comment by joewiz** [comment]
Closing in favor of #139 - a more comprehensive examination of the issues.
