### ISSUE TITLE
enhancement request: split editor panel

### ISSUE THREAD

**Issue by christophe-g** [eXist-db/eXide#13]
Hi,

I would love to have the possibility to split the main editor panel into more (e.g to compare codes between modules, ...) 

Is there any chance to see this in the future ? 

Cheers and thanks
C.

**Comment by shabanovd** [comment]
do you mean versioning?

On Thu, Jan 31, 2013 at 5:08 PM, christophe geiser <notifications@github.com

> wrote:
> 
> Hi,
> 
> I would love to have the possibility to split the main editor panel into
> more (e.g to compare codes between modules, ...)
> 
> Is there any chance to see this in the future ?
> 
> Cheers and thanks
> C.
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/wolfgangmm/eXide/issues/13.

## 

Dmitriy Shabanov

**Comment by christophe-g** [comment]
Oh, versioning would be great as well (intregrated with eXgit ??). 
Here I was just talking about ui enhancement: two panels in the editor, one with a set of tabs on the left, the other one on the right (similar to what you have in oXygen for instance). 
Cheers,
C.

**Comment by joewiz** [comment]
@wolfgangmm Do you agree we should close this as "won't fix"? This is a nice idea, but not sure it's worth the effort since you can achieve the same effect by opening two browser windows.

**Comment by joewiz** [comment]
Closing as wontfix - a nice idea, and PRs certainly welcome, but clearly no desire on the part of the developers to make this happen, at least for now.
