### ISSUE TITLE
Transfer eXide repository to exist organization

### ISSUE THREAD

**Issue by joewiz** [eXist-db/eXide#144]
The app has risen from an experimental app to improve the old Sandbox application to an app of central importance to eXist. If being included in the list of autodeployed xars and having an entry in eXist's task bar entry is any measure of an app's importance to eXist, then eXide certainly meets the bar for living in the official eXist organization.

**Comment by dizzzz** [comment]
+1  the good old sandbox....

**Comment by joewiz** [comment]
@adamretter wrote in a duplicate issue, titled, "Should this move to the eXist-db GitHub?":

> This is just a question rather than a suggestion.
> 
> It feels to me like this is seen as part of eXist-db and is used by many eXist-db users. Perhaps it would benefit by improved visibility, issues and contributors if it was moved to the eXist-db organisation on GitHub.
