### ISSUE TITLE
Switch to xqlint for syntax highlighting of query results

### ISSUE THREAD

**Issue by joewiz** [eXist-db/eXide#147]
Several attempts at fixing #108 had unintended side effects (and thus were abandoned). While there's probably a solution to that issue, it occurs to me that pretty-print.xql does just a so-so job because it essentially re-implements serialization in XQuery. Rather than continuing to expand it with other output modes, eXist already does an excellent job of serializing, and xqlint already does an excellent job of applying syntax highlighting. 

Perhaps we should switch eXide to using xqlint for syntax highlighting of query results. Atom-existdb does (see https://github.com/wolfgangmm/atom-existdb/blob/master/lib/existdb.coffee#L145-L152 and https://github.com/wolfgangmm/atom-existdb/blob/master/lib/xquery-helper.coffee#L7-L14) this successfully. atom-existdb currently assumes XML output, so doesn't currently support JSON or adaptive output, but I'm guessing JSON would be very straightforward to support, and adaptive could work if exist-db were to add native support for adaptive serialization.

The only thing we'd lose is the match highlighting of query results. And we could probably find a workaround for that - perhaps by extending adaptive serialization with some match highlighting markers.

**Comment by duncdrum** [comment]
I ll throw highlight.js into the ring here as well. I run into highlighting  problems with both, so some more work would be required. It just seems that highlight has a broader user base. Personally, I like their dev tools, but the demands of a code-editor are quite different from highlighting static code examples.

**Comment by joewiz** [comment]
Closed as completed in https://github.com/eXist-db/eXide/pull/491 by @ccheraa.
