### ISSUE TITLE
Should this move to the eXist-db GitHub?

### ISSUE THREAD

**Issue by adamretter** [eXist-db/eXide#150]
This is just a question rather than a suggestion.

It feels to me like this is seen as part of eXist-db and is used by many eXist-db users. Perhaps it would benefit by improved visibility, issues and contributors if it was moved to the eXist-db organisation on GitHub.

**Comment by wshager** [comment]
dup of #144

**Comment by joewiz** [comment]
@adamretter I quoted your comment over in #144.

**Comment by joewiz** [comment]
@adamretter There's a similar proposal about monex at https://github.com/wolfgangmm/monex/issues/39.
