### ISSUE TITLE
eXide does query encoding on path names, which is wrong

### ISSUE THREAD

**Issue by hungerburg** [eXist-db/eXide#151]
Steps to reproduce:
- In dashboard load collections
- create collections "ABC" and "A=B" in the root
- store some resources there, eg. "test.html"
- try to edit them in eXide
- /ABC/test.html will open
- /A=B/test.html will open, but one will not see it in the directory panel and one cannot open it from inside of eXide (pun intended)

Looking under the hood of eXide, links below, I see:
- http://localhost:8080/exist/apps/eXide/modules/collections.xql?root=/db/ABC&view=r
- http://localhost:8080/exist/apps/eXide/modules/collections.xql?root=/db/A=B&view=r

Looking under the hood of Dashboard and REST I see:
- http://localhost:8080/exist/apps/dashboard/plugins/browsing/contents/?collection=/db/A=B
- http://localhost:8080/exist/rest/db/A=B

From what I have learned, the call to xmldb:encodeURI at the very end of collections.xql is at fault. I do not have the means to debug further.

**Comment by joewiz** [comment]
@hungerburg Could you please provide the versions of eXist and eXide that you used for these tests?

**Comment by joewiz** [comment]
Related: 
- https://github.com/wolfgangmm/eXide/issues/119
- https://github.com/wolfgangmm/eXide/issues/77
- https://github.com/wolfgangmm/eXide/issues/19

**Comment by hungerburg** [comment]
@joewiz eXist current develop, eXide shows no updates, so latest? The entry point is in the very end of collections.xql that did not change for a long time. The error message reads: `{ "status" : "fail", "#text" : "Collection /db/A%3DB not found. Could not locate collection: /db/A%3DB" }` with the equals sign encoded.

@dizzzz Actually the subject is wrong in more ways than a typo: in a query string the equals sign needs no encoding, https://tools.ietf.org/html/rfc3986#section-3.4 -  strictly it is HTML form submission `x-www-form-urlencoded` that needs it, https://tools.ietf.org/html/rfc1866#section-8.2.1.

**Comment by tgraham-antenna** [comment]
The eXide "DB Manager" similarly cannot delete collections with names containing "=".  Nor could it delete a "${env.JOB_NAME}" collection that I managed to create in error when using the 'xdb:store' Ant task.

FWIW, the Java client could delete those collections.

**Comment by joewiz** [comment]
I started to do some tests tonight, thinking that I could get to the bottom of the eXide issues reported here and in the other linked issues above. 

What I found, though, was unexpected to me - and as a result I'm left quite confused.  I had thought the Java admin client would be the most rock solid implementation of any tool, but I found it doing strange things.  I also tested oXygen's XMLRPC and WebDAV, Transmit (a macOS WebDAV client), and plain old XQuery, and didn't find any obviously coherent behavior.  

Once I understand how eXist is *supposed* to handle collection and resource names, I will certainly look into fixing the web implementations of file browsers/managers like eXide and the Dashboard > Collections view.  

Can anyone shed light on the inconsistencies I'm seeing below?

- Starting from tests at https://github.com/wolfgangmm/eXide/issues/151, I began to unravel a few issues. Hungerbug added some tests for RFC 3986 compliance of REST path processing at https://github.com/eXist-db/exist/commit/8e4cea6104702af4fc51b5d2cdedf9c36acacdb5.

- I used different interfaces to create pairs of collections like ABC, A=B; DEF; D=E

- Java admin client:
  - When you create a collection like A=B, it shows up in the list as A=B
  - But when you try to rename it, the rename dialog shows A%3DB - the equals sign is encoded!
  - Similarly, xmldb:get-child-collections('/db') returns this collection (the one we created in the Java admin client) as A%3DB

- XQuery:
  - Create collection A=B with xmldb:create-collection('/db', 'A=B')
  - Shows up in Java admin client as A=B; the rename dialog also shows just A=B, not A%3DB

- oXygen XMLRPC:
  - Create collection A=B
  - Shows up in Java admin client as A=B; the rename dialog also shows just A=B, not A%3DB
  - xmldb:get-child-collections('/db') returns the collection as A=B

- oXygen WebDAV:
  - Create collection A=B
  - same result as oXygen XMLRPC

- Transmit
  - Create collection A=B
  - same result as oXygen XMLRPC

Other....
  - In Transmit, create collection téste, shows up in java admin client, but rename dialog shows t%C3%A9ste. so does xmldb:get-child-collections. 
  - In eXide, xmldb:create-collection('/db', 'téste') returns "/db/t%C3%A9ste"
  - In eXist, `xmldb:create-collection('/db', "A-Za-z0-9_~!$&amp;'()*+,;=@.xml")` returns `/db/A-Za-z0-9_~!$&'()*+,;=@.xml`
  - The Java admin client shows this as `/db/A-Za-z0-9_~!$&'()* ,;=@.xml` - with the `+` replaced with a space. The rename dialog shows all the characters though: `A-Za-z0-9_~!$&'()*+,;=@.xml`
  - Creating this as a collection in the Java admin client works, but the rename dialog shows `A-Za-z0-9_%7E%21%24%26%27%28%29*%2B%2C%3B%3D%40.xml`.  oXygen XMLRPC and WebDAV show this decoded. Transmit shows it as decoded but can't open the collection.
  - Creating this as a collection in oXygen and control-clicking on Copy Location shows it is being handled like this: `A-Za-z0-9_%257E!$%2526%2527()*+,;=@.xml`.  Opening this in Java admin client shows this: `A-Za-z0-9_%7E!$%26%27()*+,;=@.xml`.
  - Creating this in oXygen WebDAV words, and Copy Location shows `A-Za-z0-9_%7E!$%26amp;%27()*+,;=@.xml`. Transmit can open and browse this.

- The damn collection browser only works without persistent login.
- Before the testing above I had began some changes to allow collection browser to work more like eXide, but I'm not sure this is a good idea. I'd like to better understand how things *should* work, before I go fixing the XQuery-based apps.

- Functions for encoding/decoding URIs
  - xmldb:encode('A=B') also yields A%3DB - "Encodes the string $string such that it will be a valid collection or resource path."
  - xmldb:encode-uri('A=B') yields A%3DB - same except "Returns an xs:anyURI object representing a valid XmldbURI"
  - encode-for-uri('A=B') also yields A%3DB - "Escapes reserved characters in $uri-part by replacing it with its percent-encoded form as described in [RFC 3986]."
  - xmldb:decode('A%3DB') yields A=B - "Decodes the string $string such that any percent encoded octets will be translated to their decoded UTF-8 representation."
  - xmldb:decode-uri(xs:anyURI('A%3DB')) yields A=B - "Decodes the URI $uri such that any percent encoded octets will be translated to their decoded UTF-8 representation."

**Comment by shabanovd** [comment]
#1344 address: java client rename and rendering (`+` replaced with a space) issues

**Comment by hungerburg** [comment]
I remember that most of these problems arise from careless use of the java.net.URLDecoder class functions encode() and decode() in org.exist.xmldb.XmldbURI. The name suggests that it would do the right thing, but that is not true: URLDecoder.encode() must only be used on the keys/values of data, that is to be sent by user agents when submitting "x-www-form-urlencoded" HTML forms. Likewise decode() restores such HTTP-POSTed keys/values only **after** the data has been split into key/value pairs.

Observations on your findings:
- all of xmldb:encode, xmldb:encode-uri, encode-for-uri('A=B') should NOT encode the equals sign when used on path segments
- whether xmldb:decode or xmldb:decode-uri should decode the equals sign depends on where the input data comes from

XmldbURI class is so much above my head that I did not dare touch it, not even with a long stick; see https://github.com/eXist-db/exist/commit/2c00a7b85471400b9e556f36957e043ab483300a how I worked around it in RESTServer.java and EXistServlet.java by using its method createInternal(path), that does no encoding, instead of create(path) and doing the necessary shenanigans upfront of it.

**Comment by joewiz** [comment]
Note the report from #19 (2013!):

> I create documents using an '@' sign. Example (foo@bar.com.xml). I encode my request to this url using foo%40bar.com. Everything works well until I open the document from the collection browser. The document, the '%' sign is re-encoded instead of being decoded and I get a new file called foo%2540bar.com.xml in exide. The open command from exide works as expected however.
> 
> The java admin client and the exide open command correctly display the url as foo@bar.com;

**Comment by obujor** [comment]
Are there any news on this issue?
In my case I have collections named as "name@site.com" and eXide isn't able to open them but web Collection Browser works without problems. 
Since this is an encoding issue, I looked in the source code of collection browser and there is no "xmldb:encode-uri" call so I removed "xmldb:encode-uri" from "eXide/modules/collections.xql" and it works. 
What do you think about this solution?

**Comment by joewiz** [comment]
@obujor Thanks for taking a look at this. I would welcome a PR, if it comprehensively fixes the issue! I really got stuck when I last looked into this (https://github.com/eXist-db/eXide/issues/151#issuecomment-285603580).

**Comment by obujor** [comment]
@joewiz I found that in eXist-db v 3.* were fixed a lot of problems with special characters in the name. So I think "encode-uri" was there in order to work in eXist-db v 2. So this can be an issue if eXide has to be compatible with all versions of eXist-db.
Are new versions of eXide compatible with old eXist-db versions?

**Comment by joewiz** [comment]
@obujor Interesting! That would be great. The current version of eXide already requires eXist v3.4.0, so compatibility with v2.x is not a concern.

**Comment by obujor** [comment]
@joewiz Very good. I'll do some more testing and provide a PR.

**Comment by joewiz** [comment]
@obujor Wonderful! I'll be happy to test it.

**Comment by joewiz** [comment]
@obujor Thank you so much for this contribution! Your work passed all of the tests. Certain quirks remain in eXide due to the tendency of the app (e.g., `src/resources.js`) to rely on a resource's `name` (which tends to be uri-decoded for display) instead of its `key` (which is strictly for the application's own usage). I think we'll need to address that in a separate issue. 

The best handling of resource and collection names in eXist are WebDAV clients like oXygen and Transmit. Create a new collection named `AéB` or `A你好B`, and these clients successfully create, rename, and delete the resources. eXide will create them and display them correctly but fails to delete them. The Java admin client will create them but then displays them as url-encoded: `A%C3%A9B` and `A%E4%BD%A0%E5%A5%BDB`.

In addition, eXist's functions for creating and deleting collections are not symmetrical. For example:

```xquery
xquery version "3.1";

let $col-name := "AéB"
return
  (
    xmldb:create-collection("/db", $col-name),
    xmldb:remove("/db/" || $col-name)
  )
```

This query will fail with the following error:

> exerr:ERROR Could not locate collection: /db/AéB [at line 7, column 5]

So I think there are some application-level issues, as well as some function design issues. Hopefully we can identify these and figure out the appropriate repo for reporting these.

**Comment by obujor** [comment]
@joewiz For me is a privilege to contribute to this project.
Yes, it seems eXist still has some problems with special characters in paths.
I'll check the new issue about `src/resources.js` and try to help.

**Comment by hungerburg** [comment]
@joewiz @obujor In addition to checking with utf special chars, you should also test with ascii special chars, eg. is it fine now, to have a collection or resource by the name "A=B", "A+B" or "A@B", etc?

**Comment by obujor** [comment]
@hungerburg you can have collections with name "A=B" and "A@B" but not with "A+B", I don't know why, it could be because of the issue described by @joewiz previously.

**Comment by hungerburg** [comment]
@obujor Would you check with any of these: `~!$&'()*+,;=@:` - and also `#` - which webdav can create? (Do not do so on a production system…)

**Comment by joewiz** [comment]
@hungerburg As @obujor stated correctly, there is still an issue with "A+B". Namely, you can create a collection called `A+B` either via the File > DB Manager or via the `xmldb:create-collection` function, but eXide will display the collection as `A B`. However, I would argue that this behavior is not eXide's fault but rather is a problem with the eXist core. With @obujor's PR, eXide now simply relies on eXist's xmldb URI-related functions to do the right thing. I did identify an additional group of additional eXide-specific issues, and I opened a new issue for this: #187. 

As for issues like `A+B`, `~!$&'()*+,;=@:`, and `#`, I have initiated a clean new issue in the main eXist repo to address these, focusing first on `A+B`, in the hope that a small test case will help build up steam around this issue: https://github.com/eXist-db/exist/issues/1824. Please chime in! Let's halt further substantive discussion here and move our efforts to these new issues. This issue covers many things about both eXide and eXist that have already changed.
