### ISSUE TITLE
xqlint silently fails with final XQuery 3.1 map syntax

### ISSUE THREAD

**Issue by joewiz** [eXist-db/eXide#153]
Trying to use eXide's XQuery > Run as Test feature to run an xqsuite test like https://github.com/wolfgangmm/exist/blob/develop/test/src/xquery/xquery3/strconstr.xql in eXide silently fails. The console indicates that xqlint has choked on the map syntax:

```
Running xqlint...
eXide.min.js:27 Error while parsing XQuery: syntax error, found ':'
while expecting ':='
at line 8, column 13:
...: "Chris",
      "value": 10000,
      "taxed_value": 10000 - (1...
```

Changing the map syntax to use the old XQuery 3.1 draft syntax allows the Run as Test to proceed. 

I'm guessing this would be fixed if we update eXide's xqlint to the current version - as started in https://github.com/wolfgangmm/eXide/pull/141.

Even with the syntax change, Run as Test fails with its own error:

```
<exception>
    <path> /db/apps/eXide/modules/run-test.xql </path>
    <message> exerr:ERROR XPTY0004: The actual cardinality for parameter 1 does
        not match the cardinality declared in the function's signature:
        test:suite($functions as function+) item()*. Expected cardinality: one
        or more, got 0. [at line 15, column 27, source:
        /db/apps/eXide/modules/run-test.xql] In function: test:suite(function+)
        [15:16:jar:file:/Applications/eXist-db.app/Contents/Resources/eXist-db/exist.jar!/org/exist/xquery/lib/xqsuite/xqsuite.xql]
    </message>
</exception>
```

But that's for another issue!

**Comment by joewiz** [comment]
(Note: the problem with the "run as test" error message is reported in #155 and fixed in #156.) The xqlint problem remains.

**Comment by duncdrum** [comment]
@joewiz This should be fixed in exist4.0.0 no?

**Comment by joewiz** [comment]
@duncdrum Nope, it's xqlint's fault, not eXist's.

**Comment by joewiz** [comment]
The final outstanding issue from the original report, an issue with xqlint, was closed in https://github.com/eXist-db/xqlint/pull/1.
