### ISSUE TITLE
Unexpectedly additive login requests

### ISSUE THREAD

**Issue by joewiz** [eXist-db/eXide#157]
In eXide, logging in, then logging out and logging back in again, results in `n + 1` more login requests to login.xql.  So the first login results triggers the expected number of requests to login.xql, 1. The 2nd login triggers 2 requests. The 3rd triggers 3, and so on.  The screenshots below show eventually 10 requests are being made!

1. Logins without "remember me"

> ![screen shot 2017-03-12 at 2 31 56 pm](https://cloud.githubusercontent.com/assets/59118/23834707/3dfbae7e-0731-11e7-9c57-7a4cd334148d.png)

2. Then, switching to "remember me"

> ![screen shot 2017-03-12 at 2 33 41 pm](https://cloud.githubusercontent.com/assets/59118/23834710/44da2cf2-0731-11e7-8c87-0ae66c04c25c.png)

**Comment by shabanovd** [comment]
Also, when tab loses focus and get it back login request triggered.

**Comment by joewiz** [comment]
Thankfully, I have not observed this problem in ages.
