### ISSUE TITLE
Clear Dirty State When New Document Is Created

### ISSUE THREAD

**Issue by Flamenco** [eXist-db/eXide#16]
The initial state of a new document is dirty and always prompts to save, even when the I have not entered any information.  I think the dirty state should only be set if the user has modified the new 'template'.

**Comment by wolfgangmm** [comment]
Fixed in 8db0b2a25b9d1b38647bdf28d28e0f8b16e44b4e

**Comment by joewiz** [comment]
Thanks!  This is a great improvement!
