### ISSUE TITLE
Use "Download app" item in the Application menu, sub-collections in a .xar are lost.

### ISSUE THREAD

**Issue by jesselet** [eXist-db/eXide#165]
Test for Java 1.8.0_131 + eXist-db 3.1/3.2/3.3 + eXide 2.3.3

**Comment by joewiz** [comment]
Steps to reproduce your test, please?

**Comment by dizzzz** [comment]
e.g. please could you provide a screenshot? did you clean your browser cache? What about the Browser type plus version?

**Comment by jesselet** [comment]
#### Test packages

eXist | Date       | Package
------|------------|-------------------------------------------------
3.0   | 2017-02-09 | https://bintray.com/existdb/releases/exist/3.0
3.1.0 | 2017-03-07 | https://bintray.com/existdb/releases/exist/3.1.0
3.1.1 | 2017-03-22 | https://bintray.com/existdb/releases/exist/3.1.1
3.2.0 | 2017-05-02 | https://bintray.com/existdb/releases/exist/3.2.0

NOTE: Release date from http://www.exist-db.org/exist/apps/wiki/blogs/eXist/

#### Test steps

1.Click eXide menu [Application / New application] to create an XQuery application.
2.Open expath-pkg.xml in this application.
3.Click eXide menu [Application / Download app] to download this application.
4.Check items in the .xar

#### Test results

Java: 1.8.0_131 (64-bit)
Chrome: 58.0.3029.110 (64-bit)

eXist | Shared Resources | eXide | Result
------|------------------|-------|--------
3.0.0 | 0.4.0            | 2.2.0 | OK
3.0.0 | 0.4.0            | 2.3.2 | OK
3.0.0 | 0.4.0            | 2.3.3 | LOST
3.1.0 | 0.4.0            | 2.3.2 | OK
3.1.0 | 0.4.0            | 2.3.3 | LOST
3.1.1 | 0.4.2            | 2.3.2 | OK
3.1.1 | 0.4.2            | 2.3.3 | LOST
3.2.0 | 0.4.2            | 2.3.2 | OK
3.2.0 | 0.4.2            | 2.3.3 | LOST

NOTE: LOST (All collections in the XQuery application are lost)

**Comment by olvidalo** [comment]
Can confirm. The problem seems to be that in the latest commit e7d6fd54e8181cdd75f4ee196c407ebcbe141e24, `dbutil:scan-resources` is now used for building the list of zip file entries instead of `dbutil:scan`. `dbutil:scan-resources` does not recurse into subcollections, whereas `dbutil:scan` does.

See https://github.com/wolfgangmm/eXide/commit/e7d6fd54e8181cdd75f4ee196c407ebcbe141e24#diff-ca873483dbb97521581d2c2ad62fe101

**Comment by joewiz** [comment]
@olvidalo @jesselet My mistake then! Thanks for your testing and analysis. See also https://github.com/wolfgangmm/eXide/pull/158#discussion_r112287949 for context. I'll submit a PR shortly.

**Comment by joewiz** [comment]
If anyone is able to test #166, please let me know if it fixes the issue. It does in my testing.

**Comment by joewiz** [comment]
eXide v2.3.4 has been released with this fix. It's available via Dashboard > Package Manager, or via direct download from http://exist-db.org/exist/apps/public-repo/packages/eXide.html?eXist-db-min-version=3.0.0 or https://github.com/wolfgangmm/eXide/releases.
