### ISSUE TITLE
Error Creating New Application

### ISSUE THREAD

**Issue by ooduor** [eXist-db/eXide#169]
When I reach the last step 'done' to create the app. I get a blank popup notification at the bottom right. But teh logs have the cryptic error below.

eXide 2.3.4 on eXist 3.2
```
/home/anthony/eXist-db/webapp/WEB-INF/logs/restxq.log:399:2017-06-22 23:28:25,119 [qtp783117220-29] ERROR (ExistXqueryRegistry.java [findServices]:268) - XQuery '/db/apps/myapp/modules/app.xql' could not be compiled! Unable to compile XQuery: /db/apps/myapp/modules/app.xql: exerr:ERROR error found while loading module config: Error while loading module config.xqm: namespace URI declared by module ($$config-namespace$$) does not match namespace URI in import statement, which was: http://exist-db.org/apps/myapp/config
```

**Comment by duncdrum** [comment]
could it be that you have multiple ``config.xqm`` files in ``apps/myapp`` or multiple ``myapp``s. How does your apps directory look in collection manager?

**Comment by joewiz** [comment]
As of eXide 3.0.0, this won't be fixed. For more information please see https://github.com/eXist-db/eXide/issues/323#issuecomment-874620886.
