### ISSUE TITLE
post-in[s]tall.xql is  AWOL 

### ISSUE THREAD

**Issue by duncdrum** [eXist-db/eXide#172]
When generating a new app via exide, no post-install.xql is generated: pre-install however is generated regardless of user input.
![screenshot 2017-08-07 19 06 27](https://user-images.githubusercontent.com/6205362/29037478-21bc7d28-7ba4-11e7-8a18-b251f94b590b.png)
![screenshot 2017-08-07 19 06 51](https://user-images.githubusercontent.com/6205362/29037479-23bb8704-7ba4-11e7-90b9-89c822a2780a.png)

If we always generate a pre-install the field should indicate this, similarly providing a name for a post-install script should act like providing a name for pre-install. 

The repo.xml of the app however is consistent with user input. 
```xml
    <prepare/>
    <finish>post-intall.xql</finish>
```
So now we have a call to a non-existing post-script, and a no call for the existing pre-script. 
I made some progress with re-working exide's scaffolding, but a PR is still some ways off. 
Exist 3.4.0 
Java 1.8.144
macOS 10.12.6
eXide 2.4.0

**Comment by duncdrum** [comment]
@wolfgangmm this i kind of important to what i m working on right now, could you confirm if always generating a ``pre-install.xql`` even when its not referenced in ``repo.xml`` is a bug or a feature?  For app scaffolding would you recommend to always include a ``pre-install.xql``  or should the user be able to decide against it?

**Comment by joewiz** [comment]
@duncdrum The stock pre-install.xql module really only exists to set up the index configuration file before data is loaded. If pre-install.xql is omitted from an app, collection.xconf basically has no effect. But it makes sense that if you delete the text in this field (indicating you do not want a pre-install.xql module) and specify that a post-install.xql module be created, the app generator should respect your preferences. Let me know if you need help investigating a fix, but if you're able to submit a PR I would be happy to review it.

**Comment by duncdrum** [comment]
thanks @joewiz I ll look into a fix, but I'm swamped with work. So it might take some time.

**Comment by duncdrum** [comment]
found another one when mocking a hasty user selecting ``empty-package`` combined with ``library`` without touching the automatically filled in  ``pre-install.xql`` field creates this in ``repo.xml``:
```xml
<type>library</type>
<target>foolib</target>
<prepare>pre-install.xql</prepare>
<finish/>
```

but not the actual ``pre-install.xql`` file

**Comment by joewiz** [comment]
As of eXide 3.0.0, this won't be fixed. For more information please see https://github.com/eXist-db/eXide/issues/323#issuecomment-874620886.
