### ISSUE TITLE
the element contains "||", throw error

### ISSUE THREAD

**Issue by jesselet** [eXist-db/eXide#173]
```
xquery version "3.1";
(: Version:
 : Windows 7 SP1 (64-bit)
 : JRE 1.8.0_141 (64-bit)
 : eXist 3.4.0
 : eXide 2.4.0
 : Chrome 60.0.3112.90 (Official Build) (64-bit)
 :)
try {
    <e>||x</e>
} catch * {
    $err:code, (:XPST0003:)
    $err:description (:No closing end tag found for element constructor: e:)
}
```

**Comment by joewiz** [comment]
Moved to https://github.com/eXist-db/exist/issues/1828, as this is a problem with the eXist core, not specific to eXide. 

@jesselet Thank you for reporting this! I'm sorry I completely missed it until now.

**Comment by duncdrum** [comment]
to enable the move command we need to enable the bot in this repo by adding `/.github/move.yml`
