### ISSUE TITLE
UI bug: button row when decreasing window size 

### ISSUE THREAD

**Issue by duncdrum** [eXist-db/eXide#174]
![screenshot 2017-09-06 10 30 32](https://user-images.githubusercontent.com/6205362/30102028-9fc132f2-92ee-11e7-8fcd-837009905df5.png)

The button row (new, new xquery, …) breaks and appears under the outline pane.
Tested on current: macOS Safari, Chrome and FF. To reproduce simple make browser windows smaller.

**Comment by joewiz** [comment]
Dupe of #83?

**Comment by duncdrum** [comment]
yup
