### ISSUE TITLE
Build failed at Optimizing xqlint

### ISSUE THREAD

**Issue by obujor** [eXist-db/eXide#182]
I have an issue building eXide, after launching ant command I get an error on Optimizing xqlint target.

Here is a portion of the error:

> check-rhino-available:`
 get-rhino:
xqlint:
     [echo] Optimizing xqlint ...
     [java]
     [java] Tracing dependencies for: main
     [java] java.lang.StackOverflowError
     [java]     at org.mozilla.javascript.NativeObject.execIdCall(NativeObject.java:185)
     [java]     at org.mozilla.javascript.IdFunctionObject.call(IdFunctionObject.java:129)
     [java]     at org.mozilla.javascript.ScriptRuntime.applyOrCall(ScriptRuntime.java:2521)
     [java]     at org.mozilla.javascript.BaseFunction.execIdCall(BaseFunction.java:300)
     [java]     at org.mozilla.javascript.IdFunctionObject.call(IdFunctionObject.java:129)
     [java]     at org.mozilla.javascript.optimizer.OptRuntime.call2(OptRuntime.java:76)
     [java]     at org.mozilla.javascript.gen.__support_xqlint_r_js_1._c_HOP_305(Unknown Source)
     [java]     at org.mozilla.javascript.gen.__support_xqlint_r_js_1.call(Unknown Source)
     [java]     at org.mozilla.javascript.optimizer.OptRuntime.callName(OptRuntime.java:97)
     [java]     at org.mozilla.javascript.gen.__support_xqlint_r_js_1._c_grow_234(Unknown Source)
     [java]     at org.mozilla.javascript.gen.__support_xqlint_r_js_1.call(Unknown Source)
     [java]     at org.mozilla.javascript.optimizer.OptRuntime.callName(OptRuntime.java:97)
     [java]     at org.mozilla.javascript.gen.__support_xqlint_r_js_1._c_grow_234(Unknown Source)
     [java]     at org.mozilla.javascript.gen.__support_xqlint_r_js_1._c_expr_op_290(Unknown Source)
     [java]     at org.mozilla.javascript.gen.__support_xqlint_r_js_1.call(Unknown Source)
     [java]     at org.mozilla.javascript.optimizer.OptRuntime.callName(OptRuntime.java:97)
     [java]     at org.mozilla.javascript.gen.__support_xqlint_r_js_1._c_expr_op_290(Unknown Source)
     [java] js: exception from uncaught JavaScript throw: java.lang.StackOverflowError
    BUILD FAILED
    ..eXideDev\build.xml:110: Java returned: 3`

Any ideas?

**Comment by joewiz** [comment]
Did you follow the directions for building in the readme - in particular pulling in submodules?

**Comment by obujor** [comment]
Yes, I did.

**Comment by joewiz** [comment]
I'm not getting that on my machine, even with a fresh checkout of source (`develop` branch). Can you confirm you're also using the current HEAD of the develop branch? If so, then what OS and version, version of Java, and version of Ant?

**Comment by obujor** [comment]
Yes, it's HEAD of the develop branch, Windows 7, Java 9 and Ant 1.9.9. I tried also on Ubuntu and it's working.

**Comment by obujor** [comment]
I figured out, the problem was that my windows is a 32bit machine and in order to get Rhino working "32bit" Ant property has to be set, this feature was added in this [pull request](https://github.com/eXist-db/eXide/pull/20). I added "32bit=true" in "build.properties" and now it's working.

Now my question is, can this property be set automatically?

**Comment by dizzzz** [comment]
glad you found it; few 32bit, that is a long time ago :-) Java8+ is 64bit only no?

**Comment by obujor** [comment]
:) Java8 has 32 bit support, I think Java9+ is only 64.

**Comment by dizzzz** [comment]
ok thnx
