### ISSUE TITLE
Not sure if this line is valid

### ISSUE THREAD

**Issue by dizzzz** [eXist-db/eXide#184]
https://github.com/eXist-db/eXide/blob/c20bf61f75a40d841e53795993e7fc89858e6c1c/modules/upload.xql#L72

**Comment by joewiz** [comment]
Is there an error you’ve encountered that you’re trying to track down? Or just revieweing the code for possible problems?

**Comment by dizzzz** [comment]
sorry you are right..... Ill close this one, and add my comments in https://github.com/eXist-db/eXide/issues/176
