### ISSUE TITLE
Resource operations using "name" instead of "key" are prone to fail

### ISSUE THREAD

**Issue by joewiz** [eXist-db/eXide#185]
In https://github.com/eXist-db/eXide/blob/develop/src/resources.js, which is responsible for taking user input for operations on resources and crafting HTTP requests to https://github.com/eXist-db/eXide/blob/develop/modules/collections.xql for completing those requests, the js code frequently conflates a resource's `name` (used for user-facing display) with its `key` (used for under-the-hood identification of resources). As a result, operations can fail depending on if the resource name contains URL-encoded characters.

For example, when using the File > DB Manager dialog to delete a collection created via `xmldb:create-collection("/db", "AéB")`, eXide will return a "Deletion of the following items failed: AéB" error, because it crafted the following URL: 

http://localhost:8080/exist/apps/eXide/modules/collections.xql?remove%5B%5D=A%C3%A9B&root=%2Fdb

Instead, it should have crafted this:

http://localhost:8080/exist/apps/eXide/modules/collections.xql?remove%5B%5D=%2Fdb%2FA%25C3%25A9B&root=%2Fdb

The relevant code for deleting resources is https://github.com/eXist-db/eXide/blob/develop/src/resources.js#L473 (changing `.name` to `.key`), but an ideal comprehensive fix would review all resource operations—not just resource deletion—and ensure that the code properly distinguishes between `key` and `name`.

**Comment by hungerburg** [comment]
From eXide 2.4.5 "manage" dialogue I can create a resource/collection with a + sign in its name, then later delete it, but not browse it. Also, the name is shown with the plus as a space.

https://github.com/eXist-db/eXide/blob/bbb84da166a98a91d3fdc3be6e32096afe457ca0/modules/collections.xql#L146

"name" is treated as a _query string_ while it is a _path_; Decoding query strings is not idempotent : %2b → + → space; There is no xmldb function to decode paths; Possibly do a replace ahead of decoding(s/+/%2b/g)?

**Comment by hungerburg** [comment]
@joewiz You give an example of how requests to the backend should be crafted. In my opinion, you have it wrong: One should **not** double encode, never ever; that only will give headaches. Also, the frontend should not be bothered with what encoding the filesystem uses.

**Comment by joewiz** [comment]
@hungerburg Thanks for your comments, please keep them coming! As my comments in the eXist issue indicate, I'm seeing so many inconsistencies in the eXist core (at least the xmldb functions) that it makes "fixing" eXide difficult if not impossible. It's like a game of whack-a-mole: fixing one case creates a problem for another case. I think once we fix the core and get these functions behaving properly, we'll be able to rely on these functions to do the right thing, and debug eXide much more easily. 

Once that's settled, then for eXide we'll have to figure out:

- what data does eXide's server-side XQuery functions need to provide to eXide's client-side Javascript functions? (now eXist sends each resource's "name" and "key"... does eXide need both?)
- how should eXide's Javascript functions send data back to eXide's XQuery functions? (should it refer to resources using "name" or "key"?)
- are there any quirks with "x-www-form-urlencoded" or request:get-parameter that we need to account for when passing data around? (Here I think is part of the source of the problem when users include characters like `+` in resource names...)
- are there any "illegal characters" that eXist disallows in resource/collection names because of the design of the storage system? should eXist throw and error that we display to users, or should eXide do some client-side validation? (I'm thinking of my example of "A/B" as a collection name...)

**Comment by joewiz** [comment]
@hungerburg I'm also disadvantaged in that I don't know java or javascript—just XQuery. So please forgive me if I'm not able to roll out a complete solution singlehandedly. Thanks for your patience and assistance!
