### ISSUE TITLE
@ character in file names 

### ISSUE THREAD

**Issue by Flamenco** [eXist-db/eXide#19]
I create documents using an '@' sign.  Example (foo@bar.com.xml).  I encode my request to this url using foo%40bar.com.  Everything works well until I open the document from the collection browser.  The document, the '%' sign is re-encoded instead of being decoded and I get a new file called foo%2540bar.com.xml in exide.   The open command from exide works as expected however.

The java admin client and the exide open command correctly display the url as foo@bar.com;

**Comment by joewiz** [comment]
Superseded by #151.
