### ISSUE TITLE
Post-installation issues

### ISSUE THREAD

**Issue by DutchPirate1966** [eXist-db/eXide#191]
Hi there,
I am new on the block and just installed eXist-db/eXide v4.1.0. No errors or problems showing up during installation. I installed on my laptop locally.

After playing around, I create my first simple XQuery. I encounter a few problems when trying to evaluate and run it. 

1) when I run the query then I am asked to login to localhost:8080 on a new page. I use the login that I have used before to get into eXist-db, but the result after that is an error page with: 'This page contains the following errors: error on line 1 at column 1: Document is empty. Below a rendering of the page up to the first error.' What is the problem here?

2) saving my XQuery, closing and opening it again, it gives an error message 'Content is not allowed in prolog' and it seems that the query is not recognized as query any longer. Automatic colouring of syntax elements is not working any more. I cannot use the Evaluate button (disabled). If I copy the query to a new query the Evaluate does work again and syntax colouring is working. What is going wrong here?

Please help with these issues.
Thanks, best Marco

**Comment by duncdrum** [comment]
@DutchPirate1966 
does Exide show that you are logged in?
![screen shot 2018-05-23 at 08 29 08](https://user-images.githubusercontent.com/6205362/40407066-6a584e5c-5e63-11e8-9a2c-f76b6d83ebcc.png)

is the filetype of the Xquery set to XQuery?
![screen shot 2018-05-23 at 08 29 16](https://user-images.githubusercontent.com/6205362/40407070-6d3f712c-5e63-11e8-9f80-b9b64703f7ed.png)

**Comment by DutchPirate1966** [comment]
Yes, I am logged in as Admin and the Xquery is set to XQuery

**Comment by duncdrum** [comment]
Ok. if exide shows you as logged in and you have the correct file-type things should work. If you copy the following into the editor and click on "eval" you should see the result being computed.
```XQuery
xquery version "3.1";

for $n in 1 to 3
return
    $n
```
The second error informs you that your query is not well formed. If you share the whole query i can take a look. 
As for the first mistake i m not sure. 'run' is for html preview so if you try to run a file that doesn't do any html type things, you might see the error you describe. 

Did you already have a look at the docs? http://localhost:8080/exist/apps/eXide/docs/doc.html

**Comment by DutchPirate1966** [comment]
![screen shot 05-23-18 at 11 47 am](https://user-images.githubusercontent.com/36985551/40417478-1fb1a44e-5e80-11e8-805a-0cfb22064ab5.PNG)

Okay I used your XQuery and it evaluates, but if I run it (I have to save it first to get the run button enabled) I still get the error page. That is my real problem at the moment, that running it gives me this strange empty page.

![screen shot 05-23-18 at 11 49 am](https://user-images.githubusercontent.com/36985551/40417201-7ce3bcb6-5e7f-11e8-86a4-bbabf73028e7.PNG)

**Comment by duncdrum** [comment]
"run" is trying to render an html view, but the XQuery has no html elements, so there is nothing to display.  If you change the query like this, run will display the contents without errors.
```xquery
xquery version "3.1";
<html>{
for $n in 1 to 3
return
    <p>{$n}</p>
}
</html>
```
   
If you follow this [(short) tutorial](http://www.exist-db.org/exist/apps/doc/development-starter) you can see the run button in action with the type of input it is meant to display.

**Comment by DutchPirate1966** [comment]
Okay this makes sense indeed. But what if I want to iterate an xquery over a collection of xml files and I want to export the output into a single file. That is what I intend to do eventually. I guess I have to change my XQuery to result in some HTML output then.

Outlook voor iOS<https://aka.ms/o0ukef> downloaden
________________________________

**Comment by duncdrum** [comment]
http://www.exist-db.org/exist/apps/doc/xmldb.xml
or search for "xmldb:store" in the function documentation http://www.exist-db.org/exist/apps/fundocs/index.html

if you just want xml there is no need for html (and hence no use for the run button) just evaluate an xquery that stores its generated output as a new file in the database

**Comment by duncdrum** [comment]
in any case these kind of questions are more easily handled in our public chat room
https://existdb.hipchat.com/invite/300223/6ea0341b23fa1cf8390a23592b4b2c39

GitHub issues is for bug reports, and there is no bug here.

**Comment by DutchPirate1966** [comment]
Okay thanks so much for help. I was looking for public chat box so I will take any other questions there. Thanks again

Outlook voor iOS<https://aka.ms/o0ukef> downloaden
________________________________
