### ISSUE TITLE
File Manager does not copy after a cut.

### ISSUE THREAD

**Issue by RemiKoutcherawy** [eXist-db/eXide#203]
After a Cut, File / Manage does not copy/paste but always cut/move
The button Copy works but when you paste a resource somewhere, it disappears from the original location.

To reproduce open File / Manage :
1/ Select a resource click on Cut
2/ Select a resource click on Copy
3/ Move to another collection then Paste
4/ Back to original collection, selected resource has disappeared, moved instead of copied.

The culprit is there
https://github.com/eXist-db/eXide/blob/c9739ffe63f973fbd95adff9d2b784afa7651caf/src/resources.js#L512

A cut sets  this.clipboardMode = "move"; then calls copy()
But when doing a Copy after a Cut, copy() never sets this.clipboardMode = "copy"; and performs "move"".
You cannot just add this.clipboardMode = "copy"; in copy() as it will break cut().

Related to https://github.com/eXist-db/eXide/issues/125

Here is a pull request https://github.com/eXist-db/eXide/pull/202

Rémi

**Comment by joewiz** [comment]
Fixed by #225.
