### ISSUE TITLE
Grouping attempt on declared descendant elements of context item using serialize fails and returns unrelated elements

### ISSUE THREAD

**Issue by martin-honnen** [eXist-db/eXide#204]
When I run the code

```xquery
xquery version "3.1";

declare context item := document {
<Toptag>
<text coordinates="" country="" date="yyyy-mm-dd" lang="" place="xyc" time="" id=" 123"  name="xyz" >
<div>
This is text
</div>
</text>
<text coordinates="" country="" date="yyyy-mm-dd" lang="" place="xyc" 
time="" id=" 124"  name="xyz" >
<div>
This is text
</div>
</text>
<text coordinates="" country="" date="yyyy-mm-dd" lang="" place="xyc"         time="" id=" 123"  name="xyz" >
<div>
This is text
</div>
</text>
</Toptag>
};

/*/element { node-name() }
{
  for $child in *
  group by $xml := serialize($child)
  return $child[1]
}
```

at http://demo.exist-db.org/exist/apps/eXide/index.html with the "Eval" button I get a strange result, it returns lots of elements like

```
<collection xmlns="http://exist-db.org/collection-config/1.0">
    <triggers>
        <trigger class="org.exist.extensions.exquery.restxq.impl.RestXqTrigger"/>
    </triggers>
</collection>
2
<package xmlns="http://expath.org/ns/pkg">
    <xquery>
        <namespace>http://exist-db.org/apps/site-utils</namespace>
        <file>siteutils.xql</file>
    </xquery>
   ...
```

Result I want is 

```
<Toptag>
  <text coordinates="" country="" date="yyyy-mm-dd" lang="" place="xyc" time="" id=" 123" name="xyz">
    <div>
This is text
</div>
  </text>
  <text coordinates="" country="" date="yyyy-mm-dd" lang="" place="xyc" time="" id=" 124" name="xyz">
    <div>
This is text
</div>
  </text>
</Toptag>
```

I tried to reproduce the problem with simpler input

```
xquery version "3.1";

declare context item := document {
    <root>
        <item>foo</item>
        <item>bar</item>
        <item>foo</item>
    </root>
};

*/element { node-name() }
{
    for $child in *
    group by $xml := serialize($child)
    return $child[1]
}
```

but there I get the correct result.

I am not sure what the problem is related to but I get it reproduced with repeated evals in different browsers so I guess I let you know.

**Comment by joewiz** [comment]
@martin-honnen In the 1st query you have `/*/element` but in the 2nd query just `*/element` (note the difference in the first character). Was this difference intentional?

**Comment by martin-honnen** [comment]
@joewiz, no, sorry, it was not intentional, so the problem (if it is really one) can also be reproduced with

```
xquery version "3.1";

declare context item := document {
    <root>
        <item>foo</item>
        <item>bar</item>
        <item>foo</item>
    </root>
};

/*/element { node-name() }
{
    for $child in *
    group by $xml := serialize($child)
    return $child[1]
}
```

respectively it just seems that

```
xquery version "3.1";

declare context item := document {
    <root>
        <child>foo</child>
    </root>
};

/*
```

gives the those eXide related elements (`<collection xmlns="http://exist-db.org/collection-config/1.0">
    <triggers>
        <trigger class="org.exist.extensions.exquery.restxq.impl.RestXqTrigger"/>
    </triggers>
</collection>`) while 

```
xquery version "3.1";

declare context item := document {
    <root>
        <child>foo</child>
    </root>
};

*
```

returns the root element of the declared context item. 

I will have to study the section on context item declaration in the XQuery spec more closely to understand that difference on my own.

**Comment by martin-honnen** [comment]
So I have read the spec https://www.w3.org/TR/xquery-31/#id-context-item-declarations and it says

> If VarValue is specified, then the initial context item is the result of evaluating VarValue

but then goes on to note

> In such a case, the initial context item does not obtain its value from the external environment. If the external environment attempts to provide a value for the initial context item, it is outside the scope of this specification whether that is ignored, or results in an error.

So why does eXide for the query

```
xquery version "3.1";

declare context item := document {
    <root>
        <foo>bar</foo>
    </root>
};

/
```

return me those 

```
<collection xmlns="http://exist-db.org/collection-config/1.0">
    <triggers>
        <trigger class="org.exist.extensions.exquery.restxq.impl.RestXqTrigger"/>
    </triggers>
</collection>
2
<package xmlns="http://expath.org/ns/pkg" name="http://exist-db.org/apps/shared" abbrev="shared" version="0.7.0" spec="1.0">
...
```

elements while a change to

```
xquery version "3.1";

declare context item := document {
    <root>
        <foo>bar</foo>
    </root>
};

.
```
returns me the declared context item. Why is the result of  `. is /` false?

**Comment by dizzzz** [comment]
If you specify `/*/element { node-name() }` without a collection context (`fn:collection('/db/...')`) you will query the whole database. That is exactly what you see.

I have never seen an `declare context` for a document definition, for now I assume it is not supported by eXist. Note that the database is designed/optimized for querying documents stored in the database, or document stored in a 'normal' variable.

**Comment by dizzzz** [comment]
@martin-honnen what is the exact use case for your construct? In the context of a database it doesn't make sense to me, but I guess I don't understand yet what you want to achieve.

**Comment by martin-honnen** [comment]
I was just trying to compare the results to group on the `serialize($child)` in different XQuery engines and for that it seemed to me the most compact solution is to write an XQuery containing both the code and data together, for that I tend to use the `declare context item` declaration. So no particular use case in relation to any data base use, just my way to have a compact approach to testing snippets of XQuery with different engines, and then I run into problems with eXide that I didn't understand.

As for your assumption of it not being supported, https://github.com/eXist-db/exist/blob/develop/src/org/exist/xquery/ContextItemDeclaration.java and https://github.com/eXist-db/exist/blob/master/src/org/exist/xquery/ContextItemDeclaration.java seem to indicate there is code for that. Although I am certainly qualified to tell whether that is used or not used when I access http://demo.exist-db.org/exist/apps/eXide/index.html to test a code snippet.

**Comment by joewiz** [comment]
@dizzzz Support for the context item declaration was added in https://github.com/eXist-db/exist/pull/1571. 

@martin-honnen As I read the spec, `.` is defined as the context item; see https://www.w3.org/TR/xpath-31/#id-context-item-expression. In contrast, `/` is defined as "select[ing] the root of the tree that contains the context node; see https://www.w3.org/TR/xpath-31/#unabbrev. Even more explicitly, from

> A "`/`" at the beginning of a path expression is an abbreviation for the initial step (`fn:root(self::node())` treat as `document-node()`)/ (however, if the "`/`" is the entire path expression, the trailing "`/`" is omitted from the expansion.) The effect of this initial step is to begin the path at the root node of the tree that contains the context node.

(See https://www.w3.org/TR/xpath-31/#id-path-expressions.)

Let's apply this expanded definition of the `/` abbreviation to Martin's example:

```xquery
xquery version "3.1";

declare context item := document {
    <root>
        <item>foo</item>
        <item>bar</item>
        <item>foo</item>
    </root>
};

(fn:root(self::node()) treat as document-node())
```

This returns the expected result, the `<root>` element. In contrast, replacing the body of this query with the abbreviated form, `/`, returns the equivalent of `collection()`.

Thus, I believe @martin-honnen has demonstrated a bug in eXist's implementation of the context item declaration: it is correctly setting the context item when referring to it via `.` or `self::node()` but not as `/`.

**Comment by ghost** [comment]
This issue was moved by [joewiz](https://github.com/joewiz) to [eXist-db/exist#2155](https://github.com/eXist-db/exist/issues/2155).

**Comment by dizzzz** [comment]
ok, clear. Thnx for the comments and investigation!
