### ISSUE TITLE
Problem with "New application" command

### ISSUE THREAD

**Issue by cwittern** [eXist-db/eXide#205]
When trying to create a new app from the "New application" command, there seems to be a problem with the "Target collection".  I want my application myapp1 to live in the /db/apps collection. If I entere "apps" or "db/apps" in this field, I get an error saying:

```
/db/apps/eXide/modules/deployment.xqlerr:FODC0002 err:FODC0003 $uri is a
relative URI but there is no base-URI set [at line 628, column 42,
source: /db/apps/eXide/modules/deployment.xql] [at line 628, column 42,
source: /db/apps/eXide/modules/deployment.xql] 
```
Now, when I enter "/db/apps/" in this field, I do not get an error and my application is created, but now I have two copies:  One in "/db/apps/myapp1" and another one in "/db/apps/apps/myapp1".

**Comment by duncdrum** [comment]
this should fail more gracefully when parsing user input of desired output path

**Comment by joewiz** [comment]
As of eXide 3.0.0, this won't be fixed. For more information please see https://github.com/eXist-db/eXide/issues/323#issuecomment-874620886.
