### ISSUE TITLE
"Edit descriptors" command removes dependency on tei-publisher

### ISSUE THREAD

**Issue by cwittern** [eXist-db/eXide#206]
I created a stand-alone application with tei-publisher using 4.0RC1 and exported it to a xar file.  I then installed this into an eXist instance that did not previously have tei-publisher.  As expected, the dependency statement caused tei-publisher to be installed alongside my app.  Very good!

Then I realized that I misspelled the descriptor, opened a file from the app in eXide and used the Edit descriptors command to correct that error. Upon saving, repo.xml and expath-pkg.xml where updated with the new title. However, I then realized that the original dependency on tei-publisher had been removed.  This seems to be a bug in eXide.  Maybe there should be a field for the dependencies in the descriptor dialog?  In any case, this information should be preserved.

**Comment by joewiz** [comment]
I reviewed the code (https://github.com/eXist-db/eXide/blob/develop/modules/deployment.xql#L55-L78) and can see that eXide doesn't edit the existing expath-pkg.xml file; it overwrites it with only the information from the form. I agree the best approach would be to add form fields for dependencies, which reads from existing values.

**Comment by joewiz** [comment]
As of eXide 3.0.0, this won't be fixed. For more information please see https://github.com/eXist-db/eXide/issues/323#issuecomment-874620886.
