### ISSUE TITLE
Kill query from eXide

### ISSUE THREAD

**Issue by joewiz** [eXist-db/eXide#208]
It would be great if we could kill a query after submitting it in eXide. This would save me a trip to monex.

**Comment by joewiz** [comment]
I recall from a conversation with @adamretter that killing a query in the middle of a write operation could damage the eXist 4.x database. Adam, could you remind me if this would still be the case in 5.0? (If so, I might as well close this issue!)

**Comment by adamretter** [comment]
@joewiz It depends how the query is killed, but yes stopping a write query in eXist-db can potentially damage the db integrity. Same stands for eXist-db 5.

**Comment by duncdrum** [comment]
couldn't we try to implement a check for `updating` queries which we let finish properly, bbut cancel all non-updating queries?

**Comment by joewiz** [comment]
Are updating queries currently labeled as such?

**Comment by duncdrum** [comment]
only xquery updating extension functions should be labeled as `%updating` exist's own updating function are not labeled (but this should be easy to catch)

in any case we could simply duplicate the button and function that is currently in monex in exide (and atom)

**Comment by joewiz** [comment]
Closing as damaging db integrity is a bad idea.
