### ISSUE TITLE
Query processing-instruction return incorrect results

### ISSUE THREAD

**Issue by jesselet** [eXist-db/eXide#22]
(:in eXist Admin Client - eXist 2.0 rev 18252:)
let $xml :=
&lt;r>
<?name1 string1?>{
processing-instruction name2 { "string2" },
processing-instruction name3 {}
}&lt;/r>
return $xml
(:return as follows-----------
&lt;r>
  <?name1 string1?>
  <?name2 string2?>
  <?name3?>
&lt;/r>
:)

(:in eXide:)
let $xml :=
&lt;r>
<?name1 string1?>{
processing-instruction name2 { "string2" },
processing-instruction name3 {}
}&lt;/r>
return $xml
(:return as follows-----------
&lt;r>
<?string1?>
<?string2?>
<??>
&lt;/r>
:)

**Comment by wolfgangmm** [comment]
Fixed.
