### ISSUE TITLE
Login credentials submitted via GET; switch to POST

### ISSUE THREAD

**Issue by joewiz** [eXist-db/eXide#226]
As noted via @eduarddrenth on exist-open:

> The login in eXide issues a GET request with username/password in it, for all to read. 

Agreed that POST is a better means to submit sensitive information; see https://cwe.mitre.org/data/definitions/598.html, which states:

> When sensitive information is sent, use of the POST method is recommended.

**Comment by eduarddrenth** [comment]
As I seem to remember @wolfgangmm already fixed this somewhere

**Comment by joewiz** [comment]
I checked TEI Publisher, and it already uses POST, as does Dashboard 2.x. If you see another app that still uses GET, though, please report it or open an issue in its respective repository. Thanks!
