### ISSUE TITLE
Exception during save prevents renaming the tab. (eXide version 2.0)

### ISSUE THREAD

**Issue by bkisdi** [eXist-db/eXide#26]
I use eXist-db 2.0 (installed from eXist-db-setup-2.0-rev18252.jar) on Windows XP, with Chrome version 27.0.1453.116.

Steps to reproduce:
1. Create a new document in eXide (File / New), type: XML.
A new tab is open, the name is (e.g.) new-document 2.
2. Type in something nonsense, e.g.
asdf
3. Click Save.
The Save Document dialog appears.
4. Type a name, e.g. asdf.xml
5. Click Save.
6. eXide reports: The XML parser reported a problem: fatal error at (1,1) : Content is not allowed in prolog.
7. Click OK in the error dialog.
8. Click Cancel in the Save Document dialog, as it can't be saved now.
9. Correct the error, e.g.
&lt;asdf/&gt;
10. Click Save. The document name is not asked again, it's saved as asdf.xml, BUT the tab name remains new-document 2! And it is IMPOSSIBLE to close that tab! The status bar below the editor shows /db/..../asdf.xml. Actually I can have TWO new-document 2 tabs, if I repeat this test. AND there is the \* after the tab captions as the document weren't saved.
The same bug occours if an existing document contains syntax error and is Saved As another name: the status bar is updated, but the tab caption is not!

**Comment by wolfgangmm** [comment]
Fixed. Thanks for reporting.
