### ISSUE TITLE
File / Reload changes document status to changed. (eXide version 2.0)

### ISSUE THREAD

**Issue by bkisdi** [eXist-db/eXide#27]
I use eXist-db 2.0 (installed from eXist-db-setup-2.0-rev18252.jar) on Windows XP, with Chrome version 27.0.1453.116.

Steps to reproduce:
1. Open any document.
There is no \* in the tab caption.
2. Choose File / Reload.
A \* appears in the tab caption. It can't be different form the saved state after a successful reload!
3. Choose File / Reload again.
A confirmation dialog appears, as there were unsaved changes in the window. (The wording, "Do you really want to reload the document?" does not states it explicitly, I think it should - see step 4.)
This dialog seems to be modal, but it HAS NO FOCUS! The Esc key can't close it, the Enter key inserts a new line into the document behind!
4. Click Close.
The warning in the dialog (There are unsaved changes in this document which will be lost if you close it. Do you want to continue?) is 3 lines long, but only 2 of them are visible. Could you enlarge the window?

**Comment by wolfgangmm** [comment]
Fixed by 06c8534dea597b746ba8c5d5fd3a9a52698efc61

**Comment by joewiz** [comment]
Wonderful!  Thanks for reporting the issue, @bkisdi, and fixing it, @wolfgangmm!
