### ISSUE TITLE
Having to re-authenticate on page refresh

### ISSUE THREAD

**Issue by antoinerg** [eXist-db/eXide#3]
How come do I have to re-authenticate whenever I refresh the page?  Isn't my username saved server-side in the HTTP session?

**Comment by joewiz** [comment]
I see this intermittently but have not been able to come up with a reproducible test. I'm inclined to close this unless we're able to come up with a test. Please let us know if you have any further insights.

**Comment by dizzzz** [comment]
The issue is 6 years old, eXistdb is a different product right now

**Comment by joewiz** [comment]
Agreed, let's close and look for any reproducible reports.

**Comment by wshager** [comment]
Still not fixed

**Comment by joewiz** [comment]
Right, like I said, I still see this intermittently. But we need a reproducible report. Do you have one?

**Comment by wshager** [comment]
Why close this ticket then?

Op 24 feb. 2017 23:14 schreef "Joe Wicentowski" <notifications@github.com>:

**Comment by joewiz** [comment]
Insufficient detail.

**Comment by dizzzz** [comment]
the ticket is rather unclear and unspecific. it makes no sense to try to understand the exact conditions.... waste of time.
