### ISSUE TITLE
Can Not download PDF (LaTeX Version) in exist-db Tei-Publisher application

### ISSUE THREAD

**Issue by yasiriqbal1** [eXist-db/eXide#303]
When I try to download the PDF document (Latex Version) in a tei-publisher application. Find the below-given error.

{ "details" : null, "description" : "Cannot run program "/usr/local/texlive/2020/bin/x86_64-darwin/pdflatex" (in directory "/tmp"): error=2, No such file or directory. An IO error occurred while executing the process /usr/local/texlive/2020/bin/x86_64-darwin/pdflatex: Cannot run program "/usr/local/texlive/2020/bin/x86_64-darwin/pdflatex" (in directory "/tmp"): error=2, No such file or directory [at line 179 of unknown]" }

**Comment by wolfgangmm** [comment]
Response in https://github.com/eeditiones/tei-publisher-app/issues/47. Please do not open tickets in multiple repositories.
