### ISSUE TITLE
[BUG] New Application menu entry missing

### ISSUE THREAD

**Issue by chrmos** [eXist-db/eXide#323]
**Describe the bug**
Cannot create new applications because action `New Application` is missing from menu.

![image](https://user-images.githubusercontent.com/39056714/124562076-e5392c00-de3e-11eb-9584-66bd70e8dac8.png)

**Expected behavior**
Deployment Editor dialog should pop up when clicking on `New Application` menu entry as described at [http://exist-db.org/exist/apps/doc/development-starter.xml](http://exist-db.org/exist/apps/doc/development-starter.xml)

**Context:**
 - OS: Ubuntu 20.04
 - eXist-db Version: 5.3.0
 - Java Version: openjdk 11.0.11
-  App Version: eXide 3.0.0

**Additional context**
- How is eXist-db installed? JAR installer
- Any custom changes in e.g. `conf.xml`? No

**Comment by dizzzz** [comment]
Confirmed... I found it out myself 2 minutes ago

**Comment by dizzzz** [comment]
according to @line-o it has been replaced by https://github.com/eXist-db/generator-exist

**Comment by adamretter** [comment]
@dizzzz That seems like kind of a breaking change, I now see that eXide got a major version bump. Perhaps it would be good to remove the menu item entirely and add something to the release notes?

**Comment by duncdrum** [comment]
You mean like this?

![Screenshot 2021-07-06 at 11 41 41](https://user-images.githubusercontent.com/6205362/124579158-28030000-de4f-11eb-87e1-9c49d0c397f5.png)

https://github.com/eXist-db/eXide/blob/319623a5c8cc93d5314c08ebd34b26c56653bf6a/repo.xml#L20

**Comment by duncdrum** [comment]
So yes the app generator that shipped with exide has been deprecated in the latest release. Users who wish to generate app templates can use either the [yeoman generator](https://github.com/eXist-db/generator-exist) or the [maven archetype](https://github.com/eXist-db/exist-apps-archetype). 

In the medium term we hope to introduce a standalone templating expath application, based on the yeoman generator. Contribution are welcome. 

Lastly, downgrading eXide to the version still requiriing shared-resources, will include the old app generator.

**Comment by adamretter** [comment]
> You mean like this?

@duncdrum Nope. I meant in the actual release notes for eXist-db 5.3.0 as that is where most people will likely first encounter this during an upgrade.

**Comment by chrmos** [comment]
Thanks a lot for the info! I went with the yeoman generator.

**Comment by dariok** [comment]
The main reason for these bug reports is likely that the eXist documentation is itself outdated, cf. https://github.com/eXist-db/documentation/issues/702

It’s not surprising that people come back to this when they try to read the documentation which refers to a deprecated function. That part of the docu should have been changed when this breaking change was made in eXide.
