### ISSUE TITLE
[BUG] Missing scrollbar in output area for large outputs

### ISSUE THREAD

**Issue by mweidling** [eXist-db/eXide#325]
**Describe the bug**

After evaluating a query, the output is displayed in the output area of eXide.
Since eXist-db 5.3.0 larger output where the user has to scroll to see it completely doesn't cause the area to display a scrollbar anymore.

I observed this behaviour both in FF 89.0.2 (64-bit) for Ubuntu and Chrome Version 91.0.4472.114 (Official Build) (64-bit) on Xubuntu.

**Expected behavior**

When an output is so large that I have to scroll to see it completely, I would have expected a scrollbar so I can navigate easily.

**To Reproduce**

1. Get a large XML file (e.g. https://www.deutschestextarchiv.de/book/download_xml/goethe_leben01_1811) and store it in eXist-db 5.3.0
2. Write a small query that returns the large file, e.g. `doc("/db/goethe_leben01_1811.TEI-P5.xml")//tei:TEI`
3. Observe the output area. Even though the file is huge, there is no scrollbar displayed.

**Screenshots**

Output in eXist-db 5.2.0:

![Screenshot_2021-07-07_08-08-39](https://user-images.githubusercontent.com/13831557/124708471-9f419e00-defa-11eb-9fa7-cae89e33ac9c.png)

Output in eXist-db 5.3.0:
![Screenshot_2021-07-07_08-08-07](https://user-images.githubusercontent.com/13831557/124708492-a5377f00-defa-11eb-991e-89e957366598.png)

**Context (please always complete the following information):**
 - OS: Xubuntu 18.04 LTS
 - eXist-db Version: 5.3.0

**Comment by vincentml** [comment]
I've observed the same problem that scroll bars are now missing from the output pane after upgrading eXide to version 3.0.0. The environment is eXist-db version 5.2.0 running on Windows 2012 R2.
