### ISSUE TITLE
[BUG] Save As and Manage dialogue boxes broken due to CORS error

### ISSUE THREAD

**Issue by vincentml** [eXist-db/eXide#376]
I've recently started seeing a problem in eXide resulting from a CORS error on a remote CSS resource. It looks like this new version of eXide relies on two external CSS resources that are not being retrieved successfully:

* https://unpkg.com/ag-grid-community/dist/styles/ag-grid.css
* https://unpkg.com/ag-grid-community/dist/styles/ag-theme-alpine.css

This problem appears to be occurring in Chrome but not in Firefox.

Here is a screenshot:

![image](https://user-images.githubusercontent.com/5331729/137566546-7ae3bb5b-ddfb-4748-bb90-e36a43bc23bc.png)

The full error message is not shown in the screenshot but is "Cross-Origin Resource Sharing error: Insecure Private Network"

I am using an http (not https) connection on a local network to access eXide. Is there a way to correct this problem in eXide, or should I add an SSL certificate to eXist to be able to use https?

To reproduce:

1. open eXide
2. Go to File menu -> Save As or go to File menu -> Manage
3. The dialog box appears but is distorted to the point of being unusable

This problem is occurring in eXide version 3.0.0, but is not occurring in eXide version 2.4.9.

Context:

* OS: Windows 2012 R2
* eXist-db Version: 5.3.0
* Java version: Zulu 11.0.6
* eXide app version: 3.0.0

**Comment by amclark42** [comment]
My coworkers and I ran into this too.

* OS: RedHat 6
* eXist version 5.3.0
* eXide version 3.1.1

Our websites do have SSL enabled. Thanks to @vincentml's spot-on analysis of the problem, I was able to add `https://unpkg.com` to the servers’ `Content-Security-Policy` header. The CSS loaded fine after that.

It would help to store the CSS files in eXide, rather than calling a resource from another site. I think that would fix @vincentml’s local network HTTP use case, and make it so that websites that do have SSL certificates don’t run into this (and don’t have to muck with their security policy).

**Comment by line-o** [comment]
I could not reproduce this issue accessing eXide on localhost. Do you see this issue only for something like `exist.internal`?

**Comment by vincentml** [comment]
Hi @line-o 

I'm not sure what you mean by `exist.internal`.

This problem is appearing when accessing eXide on a remote server using http. I've not been able to reproduce this problem on localhost.

**Comment by line-o** [comment]
I wanted to know if the remote host is a domain with a standard TLD.

**Comment by vincentml** [comment]
The domain name of the eXist server is has a `.net` TLD

**Comment by line-o** [comment]
I cannot reproduce this issue. On a remote exist-DB v5.3.0 instance the externally hosted CSS files were loaded without any problem.
On eXide v3.2.1 using Chrome 96.0.4664.55 on MacOS 10.15.7.
Could you check if sec-fetch-mode is set to `no-cors`?

![Screenshot 2021-11-29 at 17 03 27](https://user-images.githubusercontent.com/657222/143902514-3e46f3bf-6b19-42b8-85e4-305407209f57.png)

**Comment by line-o** [comment]
There are several open chromium issues regarding CORS access inside Private Networks:
https://bugs.chromium.org/p/chromium/issues/list?q=component:Blink%3ESecurityFeature%3ECORS%3EPrivateNetworkAccess
And it might get even more important to have CORS in order in the future:
https://groups.google.com/a/chromium.org/g/blink-dev/c/72CK2mxD47c/m/Tl59oNfABwAJ

**Comment by amclark42** [comment]
Coming back to this issue to advocate again for including a local copy of the resources from unpkg.com in eXide (along with any relevant licenses). I spent a few days without internet this weekend (router problem). I tried to work on a local instance of eXist, but found again that the Open and Manage dialog boxes are unusable without the externally-hosted CSS. (I had disabled my cache for testing page load times.)

Another solution would be to make sure that the Open and Manage dialogs are perceivable and actionable even _without_ the external resource: using `<table>`s and/or semantic HTML tags; implementing a small CSS file of must-have rules that kicks in even if the unpkg one does not; etc. I believe pretty strongly that eXide should work regardless of internet environment, and I’m willing to draft up a PR to help move this forward, if that’d be helpful.

**Comment by line-o** [comment]
A PR would certainly be appreciated. I do understand the need to have it all packaged.
Since there is already a build step and ag-grid is also listed as a dependency in package.json it is a good place to start.

Here is what `npm run build` does:
```
		"build": "node scripts/build.js prepare && npm run xqlint && node scripts/build.js",
```
So maybe we can add commands to copy the distribution files of ag-grid there. And then these should be loaded from within  the XAR-resources instead.

**Comment by line-o** [comment]
Re-reading the issue it seems only the CSS is missing. That would certainly be easy to add.

1. add `cp node_modules/@ag-grid/.../...css` to the command line in the relevant npm scripts (build, build:dev, ...).
2. modify the link element in the page template
