### ISSUE TITLE
[BUG] default-permissions from conf.xml not used when uploading from eXide

### ISSUE THREAD

**Issue by cwittern** [eXist-db/eXide#392]
> To be able to better understand you problem, please add as much information as possible to this ticket. Always test your bugs against the latest stable release of exist. We cannot provide support for older versions here on GitHub. If the version of eXist that is experiencing the issue is more than 1 major version behind the most recent release, please consider posting a question on our mailing list. 

**Describe the bug**
I configured the database to use a different set of default permissions for collections and resources, by adding "`<default-permissions collection="0775" resource="0664"/>` to the db-connection
"

**Expected behavior**

I would expect newly created files to have the permission
`-rw-rw-r--`
but they do in fact have
`-rw-r-----`

I am uploading the file using eXide 3.2.0 using the command File->Manage

**To Reproduce**
> The *best* way is to provide an [SSCCE (Short, Self Contained, Correct (Compilable), Example)](http://sscce.org/). One type of SSCCE could be a small test which reproduces the issue and can be run without dependencies. Please locate the existing test-suite and follow the examples provided there:

I can't think of an SSCCE way to do this, so please follow the description above.

**Unit Test**
Xquery code is tested via [XQSuite - Annotation-based Test Framework for XQuery](http://exist-db.org/exist/apps/doc/xqsuite.xml) test. 
```Xquery
xquery version "3.1";

module namespace t="http://exist-db.org/xquery/test";
declare namespace test="http://exist-db.org/xquery/xqsuite";

<-- Adjust to your reported issue -->
declare
    %test:assertTrue
function t:test() {
    1 eq 1
};
```

Javascript code uses [mocha](https://mochajs.org) 

```javascript
const assert = require('assert')

// this is a dummy test 
describe('Array', function () {
  describe('#indexOf()', function () {
    it('should return -1 when the value is not present', function () {
      assert.strictEqual([1, 2, 3].indexOf(4), -1)
    })
  })
})
```

**Integration Test**
For UI and browser based testing we use [cypress.js](https://www.cypress.io)

```javascript
// adjust as necessary
describe('The app', function() {
  it('should load', function() {
    // Go to app start page
    cy.visit('/app/index.html')
  })
```

If none of the above is working, please tell us the exact steps you took when you encountered the problem:
1. Go to '...' File->Manage
2. Click on '....'  the upload icon, upload a file to the database, click on "Close"
3. Scroll down to '....'   Look at the files displayed

**Screenshots**

**Context (please always complete the following information):**
 - OS: [e.g. macOS 10.14.6]  Ubuntu 20.04
 - eXist-db Version: [e.g. 5.1.1] eXist-db 5.3.0
 - Java Version: [e.g. Java8u121] 
 openjdk 11.0.11 2021-04-20
OpenJDK Runtime Environment (build 11.0.11+9-Ubuntu-0ubuntu2.20.04)
OpenJDK 64-Bit Server VM (build 11.0.11+9-Ubuntu-0ubuntu2.20.04, mixed mode, sharing)

-  App Version: [e.g. 1.0.0]  eXide 3.2.0
 
**Additional context**
- How is eXist-db installed? [e.g. JAR installer, DMG, … ]
- Any custom changes in e.g. `conf.xml`?

Yes, I added `<default-permissions collection="0775" resource="0664"/>` to the <db-connection> configuration.

**Comment by joewiz** [comment]
@cwittern Could you please trim any sections from the issue template that you haven't filled in? This will help people who are scanning your issue to see just the relevant info you've added to the issue.

eXide simply uses the `xmldb:store` function to store resources uploaded via File > Manage, and this is performed as the named user, so there is nothing eXide specific to the permissions assigned to a collection or resource created/stored with eXide. The only override eXide performs is that XQuery files are made executable by all (and perhaps this should be made into a preference so that users can toggle this behavior). See https://github.com/eXist-db/eXide/blob/develop/modules/store.xql#L72-L85. 

As I see it, if `xmldb:store` isn't respecting the conf.xml permissions, then this is an eXist issue and not an eXide issue.

**Comment by cwittern** [comment]
@joewiz, you are right, I can now confirm that this problem exists also when storing the resource by other means, in this case through XML-RPC via oXygen.  So I am closing this issue now.  Sorry for the noise.
