### ISSUE TITLE
"New XQuery" creates almost empty page 

### ISSUE THREAD

**Issue by dizzzz** [eXist-db/eXide#40]
When running "New XQuery"  eXide creates almost empty page , with a character '1' to avoid syntax-validation errors; I think this should change since it looks not so nice too.

**Comment by wolfgangmm** [comment]
How would you suggest the new XQuery to look like? Just remove the "1"?

**Comment by dizzzz** [comment]
I think that is the best option, yes
unless a comment like (: type here :) would satisfy the validation part
Alternatively, we could consider the validator to ignore 'some how' an empty document with that magic string....

**Comment by joewiz** [comment]
I was confused by this too - thought it was a bug until I saw this post.

How about `'Hello world!'`?

**Comment by wolfgangmm** [comment]
When a new XQuery buffer is created, its state is now set to not-modified and validation is disabled. We can thus remove the "1" placeholder. Validation will start once the user typed something.

See 06ac994a7078586256a4491683c84ee9cd6019f0

**Comment by joewiz** [comment]
Brilliant!  Many thanks!
