### ISSUE TITLE
[BUG] "New application" not shown in Exide menu (?)

### ISSUE THREAD

**Issue by eu-genia** [eXist-db/eXide#425]
I have just installed ExistDB on localhost but cannot get started as I do not see New Application in the Application menu of Exide
![image](https://user-images.githubusercontent.com/17987728/153209964-c01cc553-1261-45e3-a33b-50bbc83810c6.png)
I am logged in with an admin account (dba)

I would expect to see "New Application"

Windows 10
exist-DB 6.0 installed from Jar
Java8.271 x 64

**Comment by joewiz** [comment]
@eu-genia Please see this note about the removal of the app generator functionality in eXide 3.x and the suggested alternative: https://github.com/eXist-db/eXide#note-concerning-exide-300.

**Comment by eu-genia** [comment]
Thank you, I was misled by the guidelines at http://gwi-exist2.gwi.uni-muenchen.de:8081/exist/apps/doc/development-starter.xml
