### ISSUE TITLE
Copy and paste doesn't work.

### ISSUE THREAD

**Issue by ksdm2e** [eXist-db/eXide#45]
On my dev-machine 

[eXist Version : 2.1]
[eXist Build : 20131214]

ctrl-c / ctrl-v doesn't work in exide.

(my source is one month old, bug maybe fixed already.)

**Comment by joewiz** [comment]
Which operating system and browser?

**Comment by ksdm2e** [comment]
windows xp, firefox 17.0.2

[didn't realized ... firefox maybe old enough to ignore?]

**Comment by dizzzz** [comment]
is it fixed in the latest exide version?

**Comment by joewiz** [comment]
There's been ample opportunity to respond. Please reopen if you still have a problem.
