### ISSUE TITLE
[BUG] Cannot browse a collection which has a space in its name

### ISSUE THREAD

**Issue by adamretter** [eXist-db/eXide#459]
I can create collections in eXist-db by URI encoding the space, for example this query:

```xquery
xmldb:create-collection("/db", "spaced%20thing"),
xmldb:create-collection("/db/spaced%20thing", "more%20spaced")
```

However if I try and view the contents of `/db/spaced thing` by navigating to it in the `directory` tab of eXide, then I see the following error in the Web Browser's JavaScript Console when it calls the script: `http://localhost:8080/exist/apps/eXide/modules/collections.xql?root=/db/spaced%20thing&view=r`

The response from the server is:
```
{ "status" : "fail", "#text" : ". Could not locate collection: /db/spaced thing" }
```

It looks like eXide is failing to uri-encode the collection string within `collections.xql`

I am not certain, but there may be some cross-over with https://github.com/eXist-db/eXide/issues/185#issuecomment-381887175

**Comment by joewiz** [comment]
This is fixed in v3.5.0. I believe the PR that fixed this is https://github.com/eXist-db/eXide/pull/489.
