### ISSUE TITLE
keyboard shortcut to close output window wanted

### ISSUE THREAD

**Issue by jensopetersen** [eXist-db/eXide#47]
continually revising - outputting - revising becomes clumsy when one has to hit the minute arrow every time to close to output window in order to view the code properly, so a keyboard shortcut would come in handy here

**Comment by wolfgangmm** [comment]
I added a command for this ("Navigate/Toggle results panel" in the menu). Keyboard shortcut on the mac is Cmd-Shift-F12. Please suggest a different shortcut if this doesn't work. I have problems finding unused key combinations ;-)

**Comment by jensopetersen** [comment]
Thanks a lot!

Sent from my HTC

----- Reply message -----
