### ISSUE TITLE
eXide XML Output cannot be selected and copied

### ISSUE THREAD

**Issue by jensopetersen** [eXist-db/eXide#49]
With shared-resources-0.3.9, it s no longer possible to select and copy the XML Output of a query in eXide. Even copying the whole page does not include the XML Output. With shared-resources-0.3.8, copying works fine. Unfortunately, eXide 2.0.6 requires shared-resources-0.3.9.

eXist-version: 2.1
Mac OS X 10.9.1

Tested in browsers: Chrome 31.0.1650.63, Firefox 26.0, Safari 7.0.1.

I add the ticket here, because it appears only to affect eXide.

**Comment by joewiz** [comment]
I can confirm that I have this problem with Chrome on Mac (same version profile as Jens) and on Windows 7.

**Comment by wolfgangmm** [comment]
Fixed in eXide 2.0.7
