### ISSUE TITLE
Missing default namespace declaration in eXide results pane

### ISSUE THREAD

**Issue by yamahito** [eXist-db/eXide#50]
Hi,

I have some data in an eXist database where the default namespace is set on a wrapper element (fragment), then set to empty on a child element (div).

Using a db connection in oxygen, the behaviour is as expected, so I'm happy that the data is held correctly in the database.

However, when using exist the empty default namespace declaration (xmlns="") is not displayed:

![image](https://f.cloud.github.com/assets/3420242/2149169/d66092e0-93f0-11e3-92ae-1abff9dbd271.png)

Thanks!
Tom

**Comment by wolfgangmm** [comment]
Some display issues concerning namespaces were fixed in 2.1.1
