### ISSUE TITLE
result panel: direct output dropdown grayed out after selection was made

### ISSUE THREAD

**Issue by JoernT** [eXist-db/eXide#54]
eXide Version: 2.0.1
Browser FF 27.0.1
edited file type was templated html

Dropdown allows to switch between XML output and 'direct output'. Once i clicked the checkbox (after having used the 'run' button) and changed its value it became grayed out and is not changeable any more. Even reloading did not help.

**Comment by joewiz** [comment]
Could you confirm if you are still experiencing this issue with current versions?

**Comment by joewiz** [comment]
Original reporter did not respond to prompts for updates.
