### ISSUE TITLE
Linting for xconfig files: inaccurate error wrt namespaces

### ISSUE THREAD

**Issue by vogelsgesang** [eXist-db/eXide#56]
I am currently trying to get indexing working. I entered the following code snippet from http://exist-db.org/exist/apps/doc/indexing.xml into eXide

``` xml
<collection xmlns="http://exist-db.org/collection-config/1.0">
    <index xmlns:atom="http://www.w3.org/2005/Atom">
        <fulltext default="none" attributes="no">
            <create qname="atom:title"/>
        </fulltext>
        <range>
            <create qname="atom:id" type="xs:string"/>
        </range>
    </index>
</collection>
```

Now, eXide marks `type="xs:string"` as an error with the error message "The value 'xs:string' of attribute 'type' on element 'create' is not valid with respect to its type, 'QName'."

So, either the example from the eXist documentation is wrong or this error message is misleading...

**Comment by joewiz** [comment]
I've seen this too.  If you provide the xmlns for xs, it'll pass validation.

**Comment by dizzzz** [comment]
http://exist-db.org/exist/apps/doc/getting-help.xml

import note: do not use the old full text index.

```
    <fulltext default="none" attributes="no">
        <create qname="atom:title"/>
    </fulltext>
```

**Comment by dizzzz** [comment]
@joewiz interesting, that would be a regression I think

**Comment by joewiz** [comment]
I recall seeing this with conf.xml set to validation=auto instead of no.

**Comment by vogelsgesang** [comment]
@dizzzz: Thanks for the note about avoiding the legacy index. I am not actually using this configuration file. I just copied it over from your documentation as an example since I consider your documentation to contain less errors than files which I wrote by myself.

@joewiz: No, I am talking about a different problem here. validation=no is set and eXide marks an error next to the line containing "xs:string". But saving this document in the database works fine. Only the client-side validation fails.
On the other side, if I set validation=auto, saving the document does not work anymore because the server-side validation fails.

I added the xs namespace now and everything works fine for me. Nevertheless, this message was irritating for me because eXide stated that the example from the eXist-db documentation contains an error.

**Comment by wolfgangmm** [comment]
@dizzzz: the validation error is reported by validation:validate-report($doc, doc($schema)), which is called by eXide in the background. So either validate-report is wrong and should be fixed or we filter what is returned in eXide.

**Comment by dizzzz** [comment]
@wolfgangmm interesting...... but then we should be able to reproduce.

**Comment by wolfgangmm** [comment]
``` xquery
xquery version "3.0";

let $xconf :=
    <collection xmlns="http://exist-db.org/collection-config/1.0">
        <index>
            <create qname="foo" type="xs:string"/>
        </index>
    </collection>
let $schema := doc("/db/apps/eXide/resources/schema/collection.xconf.xsd")
return
    validation:validate-report($xconf, $schema)
```

**Comment by dizzzz** [comment]
in Oxygen I get

```
System ID: /Users/xxxx/Desktop/Presentation/Validation/Untitled1.xml
Main validation file: /Users/xxxx/Desktop/Presentation/Validation/Untitled1.xml
Schema: oxygen:/eXist-db xxxx$eXist-db miniserver.local/db/apps/eXide/resources/schema/collection.xconf.xsd
Engine name: Xerces
Severity: error
Description: UndeclaredPrefix: Cannot resolve 'xs:string' as a QName: the prefix 'xs' is not declared.
Start location: 5:47

System ID: /Users/xxxx/Desktop/Presentation/Validation/Untitled1.xml
Main validation file: /Users/xxxx/Desktop/Presentation/Validation/Untitled1.xml
Schema: oxygen:/eXist-db xxxx$eXist-db xxxxx/db/apps/eXide/resources/schema/collection.xconf.xsd
Engine name: Xerces
Severity: error
Description: cvc-attribute.3: The value 'xs:string' of attribute 'type' on element 'create' is not valid with respect to its type, 'QName'.
Start location: 5:34
End location: 5:45
URL: http://www.w3.org/TR/xmlschema-1/#cvc-attribute
```

in eXide

``` xml
<report>
<status>invalid</status>
<namespace>http://exist-db.org/collection-config/1.0</namespace>
<duration unit="msec">149</duration>
<message level="Error"  line="3"  column="47">UndeclaredPrefix: Cannot resolve 'xs:string' as a QName: the prefix 'xs' is not declared.</message>
<message level="Error"  line="3"  column="47">cvc-attribute.3: The value 'xs:string' of attribute 'type' on element 'create' is not valid with respect to its type, 'QName'.</message>
</report>
```

**Comment by dizzzz** [comment]
the following works (add xs: prefix definition)

``` xml
    <collection xmlns="http://exist-db.org/collection-config/1.0">
        <index xmlns:xs="http://www.w3.org/2001/XMLSchema">
            <create qname="foo" type="xs:string"/>
        </index>
    </collection>
```

note that in the eXide generate .xconf file the `xmlns:xs="http://www.w3.org/2001/XMLSchema"`  is automatically added.

the following works as well (no prefix)

``` xml
    <collection xmlns="http://exist-db.org/collection-config/1.0">
        <index>
            <create qname="foo" type="string"/>
        </index>
    </collection>
```

I have no idea why the validation: function does not know about the xs: prefix  it might be a Xerces bug....

@vogelsgesang  for sure the documentation needs to be adjusted. or maybe we can configure xerces to support 'standard' prefixes (though OxygenXML shows the same validation issue!)

**Comment by duncdrum** [comment]
This happens to me on win7 and amazon Linux with the latest stable release. I have declared the ```xs:``` namespace and the index works correctly. You can see the config.xml [here](https://github.com/duncdrum/protoColl/blob/master/protoColl/collection.xconf).  However, the log reports:
```[eXistThread-51] ERROR (RangeIndexConfig.java [parseChildren]:87) - Invalid range index configuration: Invalid type declared for range index on :  xs:string ```
after every reindex.

**Comment by joewiz** [comment]
@duncdrum Is it possible the error you're seeing is caused by the extra space in the attribute here? 

https://github.com/duncdrum/protoColl/blob/master/protoColl/collection.xconf#L32

**Comment by duncdrum** [comment]
@joewiz I have no idea how I could have overlooked this. I was staring at the file for ages. Thanks so much

**Comment by joewiz** [comment]
I think we understand that the way to avoid the bug in eXide is to add `xmlns:xs="http://www.w3.org/2001/XMLSchema"` to the `<index>` element. If there is a problem with xerces, it should be reported in the main eXist repo.
