### ISSUE TITLE
generate expath-pkg.xml.tmpl

### ISSUE THREAD

**Issue by jensopetersen** [eXist-db/eXide#58]
If one downloads an app and unzips it, one has a copy of the installation. That's fine, but if one wishes to make modifications and rebuild it, the expath-pkg.xml.tmpl is missing. Could this file be generated as well when downloading?

**Comment by duncdrum** [comment]
I m looking into app generators for exist, but I don't understand what the advantage of having the .tmpl file as well as the working expath-pkg.xml would bring. Could either of you help me understand this.

**Comment by dizzzz** [comment]
In our build scripts we do a lot of variable substitution:

https://github.com/wolfgangmm/eXide/blob/develop/build.xml#L144

**Comment by duncdrum** [comment]
Ok i think i get it now I. As long as we are not talking about generating a template based on just any app that is installed on a system. I think that would be a bad idea for all kinds of reasons. But for apps that are developed using a generator in the first place, I think this can be solved.

**Comment by dizzzz** [comment]
from my perspective, most XAR files developed by us, are bitterly a ZIP file from the file system; this means that it is possible to unzip de XAR file, do modifications, run ant to build the XAR again. If this template file is not there, this process is not possible. Hence the request of Jens.

**Comment by duncdrum** [comment]
Yes if build.xml references a ``.tmpl`` file it should be included in the .xar. Otherwise: ``exide-> downloaded app -> rename ``.zip`` -> modify files -> call ant -> install new .xar in exist``  works fine, hence my confusion.

**Comment by dizzzz** [comment]
probably because the tmpl file is not found end hence skipped?

**Comment by joewiz** [comment]
As of eXide 3.0.0, this won't be fixed. For more information please see https://github.com/eXist-db/eXide/issues/323#issuecomment-874620886.
