### ISSUE TITLE
build fails

### ISSUE THREAD

**Issue by jensopetersen** [eXist-db/eXide#63]
Buildfile: /Users/jens/Downloads/eXide-develop/build.xml

check-rhino-available:

get-rhino:
     [echo] Downloading rhino...
      [get] Getting: https://raw.github.com/jrburke/r.js/master/lib/rhino/js.jar
      [get] To: /Users/jens/Downloads/eXide-develop/tools/js.jar
      [get] https://raw.github.com/jrburke/r.js/master/lib/rhino/js.jar permanently moved to https://raw.githubusercontent.com/jrburke/r.js/master/lib/rhino/js.jar
      [get] Getting: http://requirejs.org/docs/release/2.1.4/r.js
      [get] To: /Users/jens/Downloads/eXide-develop/tools/r.js

xqlint:
     [echo] Optimizing xqlint ...
     [copy] Copying 1 file to /Users/jens/Downloads/eXide-develop/support/xqlint
     [copy] Copying 1 file to /Users/jens/Downloads/eXide-develop/support/xqlint
     [java] js: Couldn't read source file "./support/xqlint/r.js: ./support/xqlint/r.js (No such file or directory)".

BUILD FAILED
/Users/jens/Downloads/eXide-develop/build.xml:109: Java returned: 4

**Comment by dizzzz** [comment]
since @wolfgang added a new version to the RC2, the issue might be solved?

**Comment by joewiz** [comment]
This doesn't affect the current version of eXide.
