### ISSUE TITLE
not able to open results pane in Chrome 36

### ISSUE THREAD

**Issue by JoernT** [eXist-db/eXide#66]
The results pane is placed at bottom im my case. It has been narrowed to a small stripe of just a few pixels height. 

It is not possible to change the size any more by dragging the resize bar. Effectively the results pane keeps being hidden und unusable.

**Comment by wolfgangmm** [comment]
That's why eXide should normally reset the layout if you upgrade from a previous version. Obviously this doesn't work as expected. Some questions:
1. clicking on the icon in the middle of the resize bar did not restore it?
2. do you remember which version of eXide you were running before?

**Comment by dizzzz** [comment]
@JoernT is it fixed?

**Comment by wolfgangmm** [comment]
Added menu option "Navigate/Reset editor layout" in 2.1.1, so users can reset the layout to the defaults in case anything gets messed up.
