### ISSUE TITLE
The RestXQ trigger should be added to the default collection.xconf

### ISSUE THREAD

**Issue by lcahlander** [eXist-db/eXide#69]
When an app is created from template, the collection.xconf should be:

```
<collection xmlns="http://exist-db.org/collection-config/1.0">
    <index xmlns:xs="http://www.w3.org/2001/XMLSchema">
        <fulltext default="none" attributes="false"/>
    </index>
    <triggers>
        <trigger class="org.exist.extensions.exquery.restxq.impl.RestXqTrigger"/>
    </triggers>
</collection>
```

Instead of:

```
<collection xmlns="http://exist-db.org/collection-config/1.0">
    <index xmlns:xs="http://www.w3.org/2001/XMLSchema">
        <fulltext default="none" attributes="false"/>
    </index>
</collection>
```

**Comment by dizzzz** [comment]
I am not sure, i hardly use the trigger, and some issues are reported by some users, That did not use the trigger.

Optional is better IMO =

**Comment by joewiz** [comment]
Closing as wontfix. It's easy enough to paste in the desired `<trigger>` element from the documentation, or to modify your local instance with this additional element. Alternatively, PRs are welcome with additional document templates. See where these are defined at https://github.com/wolfgangmm/eXide/blob/develop/templates/documents.xml#L3-L10.
