### ISSUE TITLE
DB Manager Delete Resource Error for a collection name with tilde character

### ISSUE THREAD

**Issue by lagivan** [eXist-db/eXide#77]
I'm facing issues while deleting collections via eXide DB Manager. It looks like eXide encodes the file/collection name replacing tilde character with `%7E`, thus, fails to delete the target. There must be a bug with handling the DB paths.

The target collection `0060-414673376---SPC_1_1~Z1-ACG387~001` was created using XQuery function `xmldb:create-collection`.

![issue_screen](https://cloud.githubusercontent.com/assets/2240347/4679321/4ee8ac08-5600-11e4-8369-23f92fc7dbb1.jpg)

**Comment by joewiz** [comment]
You said in the other thread that you created this collection with `xmldb:create-collection()`.  Did you wrap the collection name in `xmldb:encode-uri()`?  If not, you may have introduced encoding errors into the collection name.  Could you please supply a reproducible test showing this problem?

**Comment by lagivan** [comment]
Yes, I've added the same remark here in the ticket body. I do not wrap the name in `xmldb:encode-uri()` and I do not understand why it should be required. It does not affect when I read-write the data via XQuery, it's even rendered correctly in eXide, the only issue is that it fails to be deleted via eXide. So the reproducible test is the following XQuery:

```
xquery version "3.0";
xmldb:create-collection('/db/apps/ssg/data/dita', '0060-414673376---SPC_1_1~Z1-ACG387~001')
```

Do you state it's not a bug and I should be using `xmldb:encode-uri()`?

**Comment by dizzzz** [comment]
I'd say yes

**Comment by joewiz** [comment]
Superseded by #151.
