### ISSUE TITLE
The search is always one character behind

### ISSUE THREAD

**Issue by frog23** [eXist-db/eXide#8]
When using the search with the bottom search bar, the search is always one character behind in what it searches for. So when I type "exis" it will search for "exi", but when I then hit backspace and have "exi" in my search bar, it will search for "exis". This can be quite confusing.

This can be fixed easily by changing [line 17 in src/find.js](https://github.com/wolfgangmm/eXide/blob/master/src/find.js#L17) from 
`$this.input.keydown(function (ev) {`
to 
`$this.input.keyup(function (ev) {`

I check this in Firefox 18 and Chrome 24.

**Comment by wolfgangmm** [comment]
Thanks. I applied this patch.
