### ISSUE TITLE
outline panel vanishes

### ISSUE THREAD

**Issue by pherk** [eXist-db/eXide#85]
the outline panel vanishes with the second start of eXide.
- starting db
- starting exide via dashboard
- outline panel appears as expected
- closing exide tab and restarting via dashboard -> no outline panel :-)
- deleting firefox cookies
- restarting exide -> outline panel reappeares

I am using:
- exist-db latest development branch v2.2
- eXide v2.1.2
- firefox 34 ubuntu 14.04LTS

ps: I wonder that no other has this problem

**Comment by joewiz** [comment]
Are you still experiencing this problem? I'm not seeing it with current versions of eXist and eXide in Chrome.

**Comment by pherk** [comment]
no, not in the last 6-8 months

regards
Peter

Quoting Joe Wicentowski <notifications@github.com>:

> Are you still experiencing this problem? I'm not seeing it with  
> current versions of eXist and eXide in Chrome.

**Comment by joewiz** [comment]
@pherk Great, that's good news, and thanks so much.
