### ISSUE TITLE
Using 'Include all libraries' when creating a new application uses imports of shared resources templates instead of local copy

### ISSUE THREAD

**Issue by vovtz** [eXist-db/eXide#87]
Creating a new application from eXide using the option 'Include all libraries' results in a local copy of 'templates.xql' in the app's 'modules' folder, but with the module namespace still pointing to the 'shared resources' copy of 'templates.xql'. Also all of 'app.xql', 'config.xqm' and 'view.xql' use the 'shared resources' URL (http://exist-db.org/xquery/templates) to import 'templates'.

eXist-db version 2.2
# Selected options in the 'Deployment Editor'
## Application Properties
- Template: "eXist-db Design"
- Type of package: "Application"
- Include all libraries: checked
- Target collection: "Test"
- Name: "http://exist-db.org/apps/Test"
- Abbreviation: "Test"
- Title: "Test"
- Version: "0.1"
- Status: "Alpha"
- Pre-install XQuery: "pre-install.xql"
- Post-install XQuery: left empty
## Description
- Author: "Me"
- Description: "Test"
- Website: left empty
## Default Permissions
- Owner: "admin"
- Password: ""
- Group: left empty
- Mode: "rw-rw-r--"

**Comment by duncdrum** [comment]
I think this option is no more, good to close? 
P.S.: Giving users more options with respect to ``$shared-resources`` is something i m working on.

**Comment by vovtz** [comment]
@duncdrum OK with me, I'm not using eXist-db anymore.
