### ISSUE TITLE
Stuck splash screen

### ISSUE THREAD

**Issue by hungerburg** [eXist-db/eXide#96]
Splash screen gets stuck quite often, e.g. when no file to open given in initial request URL; The problem seems to be very minor, please see picture for info, behind the splash everything is fine. Here eXide 2.1.3, no update available…

Kind regards
Peter

![exide-stuck-splash](https://cloud.githubusercontent.com/assets/586972/8281551/5b218d58-18e9-11e5-817d-3c8d65717532.png)

**Comment by joewiz** [comment]
Browser/OS? Any steps to reproduce what you're seeing? Does clearing the cache (as the splash screen suggests) help or not?

**Comment by hungerburg** [comment]
@joewiz No, the suggested recipe does not work. OS is firefox (linux, windows the same.) This only happens when I browse to /exist/apps/eXide/index.html from a bookmark; eXide starts fine, when I go there from the dashboard, although the URL is the same. Firebug reports one more error:
`Error: Permission denied to access property "eXide_onload" ...n):a&&eXide.app.newDocument(a,"xquery");window.opener&&window.opener.eXide_onloa...`

**Comment by tohuuuuu** [comment]
I encounter the same if i try to open a resource in eXide, calling .../apps/eXide/index.html?open=/db/... from another "domain". Now, trying to access a js property belonging to the opener frame / window fails because of same-origin policy, i suppose. As far as i see, this callback isn't required in such cases, so why not just surround it with try{...} catch (e) {}? This way, eXide opens the file without problems even when called from a non-eXist frame.

**Comment by dizzzz** [comment]
which version of the browser? is there a known bug/new feature?
do you have extensions running that might impact jacascript execution?

**Comment by tohuuuuu** [comment]
Tested with Firefox 44 and Chromium 48 on Linux x86_64. Chromium has a more explicit error message: `Uncaught SecurityError: Blocked a frame with origin "https://<origin_host>:<origin_port>" from accessing a frame with origin "https://<origin_host>:<source_port>". Protocols, domains, and ports must match.` IMHO this is the default behaviour for browsers enforcing same-origin policy; so IMHO no bug, no new feature, not dependent to any extensions.

**Comment by joewiz** [comment]
@hungerburg @fschmitt Are you still seeing this issue?

**Comment by hungerburg** [comment]
@joewiz  I still see the issue: workstation windows 7 on same LAN as server, eXide 2.1.3, browser firefox 45.8.0 ESR. No way to find out which version of eXist-db from the dashboard, but 2.2 from Version.txt

I just noticed, that the issue does NOT appear, when I open eXide in a new tab (middle-mouse-click) on this same system! I also do not see the issue on another workstation with linux firefox 52. I also do not see the issue in linux google-chrome 57.

So, a tricky one, you choose, if this is still valid - From my position, good to close.

**Comment by joewiz** [comment]
@hungerburg So conceivably this could be an issue that affected older versions of firefox (like your 45.8.0 ESR on Windows) but not current versions (like your 52 on Linux)?  If we can confirm that this just affects older versions of Firefox, then I'm inclined to close it.  I know it's not always easy to upgrade browsers in enterprise settings, but unless eXide had a developer with the affected systems/versions who was inclined to fix it (or do you know of someone?), I'm afraid I can't realistically see this getting much traction.

**Comment by hungerburg** [comment]
There is a known workaround (opening eXide in new tab, a.k.a. from a "target=_blank" link in at least of one of the affected browsers of those only the affected one is not EOL. Bug no longer significant. Close.
